### ISSUE TITLE
Springfox not generating different swagger entries for operations with same base path, but one endpoint has query parameters

### ISSUE THREAD

**Issue by codependent** [springfox/springfox#1053]
Springfox doesn't generate correctly the swagger doc for a simple case like this one:

`GET /api/departments`  - Gets all department
`GET /api/departments?name=IT` - Gets a department with name passed as query parameter

This is the Spring Controller:
```
@ApiOperation(value = "Gets all departments", notes = "", tags = {"departments"})
@RequestMapping(value="/departments", produces=MediaType.APPLICATION_JSON_VALUE, method=RequestMethod.GET)
public List<Department> getAllDepartments(){
       ...
}

@ApiOperation(value = "Gets a department by name", notes = "", tags = {"departments"})
@RequestMapping(value="/departments", params="name", produces=MediaType.APPLICATION_JSON_VALUE, method=RequestMethod.GET)
public Department getDepartmentByName(@RequestParam String name){
	...
}
```
The generated swagger file only contains the `GET /api/departments` entry, not a trace of the one with the query filter.

**Comment by codependent** [comment]
The problem comes from:

`springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper.mapApiListings()`

```
protected Map<String, Path> mapApiListings(Multimap<String, ApiListing> apiListings) {
    Map<String, Path> paths = newHashMap();
    for (ApiListing each : apiListings.values()) {
      for (ApiDescription api : each.getApis()) {
        paths.put(api.getPath(), mapOperations(api, Optional.fromNullable(paths.get(api.getPath()))));
      }
    }
    return paths;
}
```
There are two ApiDescription, both of them have the same path `/departments`. But since io.swagger.models.Path only has one attribute `private Operation get`, it doesn't support this case.

Any ideas?

**Comment by codependent** [comment]
After digging into this, maybe this is a swagger spec limitation and we can't define for a same path multiple instances of the same operation. Is this right?

**Comment by dilipkrish** [comment]
That is correct. Once we add support in the spec for supporting RFC 6570, it should work as you'd expect it to. [Here is](https://github.com/swagger-api/swagger-spec/issues/291) the issue that relates to the problem. 

Until then, if you don't care about swagger-ui, there is support that is in incubation, where you `enableUrlTemplating` in your docket, that will atleast render the operations true to your service implementation.

**Comment by codecounselor** [comment]
There is an active thread with Swagger very closely related to this having to do with content negotiation.  https://github.com/OAI/OpenAPI-Specification/issues/146 

While the swagger spec and swagger UI do not yet support a correlation between the content type and the response schema, it does support the listing of multiple "produces" attributes.  

Until this is finalized the in a swagger release, would you support a new issue and pull request to merge, rather than overwrite paths if they differ only by their produces values?

Also, it seems that RAML does support this currently.  @dilipkrish I've noticed that you've commented this is not something you have bandwidth to contribute, are you aware of anyone else who may be considering a RAML mapping contribution?

**Comment by dilipkrish** [comment]
@codecounselor this issue has nothing to do with content negotiation. This has to do with multiple endpoints that differ based on query parameters. e.g. `findByEmail` method that looks like this `find?email={email}` and  `/findByZip` method that looks like this `/find?zip={zip}`. If you don't use the rfc6570 feature that springfox supports one of those paths would be lost because it only supports up-until `/find`

Now on your request, not sure what you're proposing, but _if it makes sense to be part of the library_ for sure we encourage PRs. If you do plan on working on it, do share your design/ideas in an issue. This will help whet the idea and also make sure its in line with the direction of this library.



The RAML support, Im not sure there is any support that supports runtime introspection. I know there are some maven/gradle plugins that do support build time specification generation. The hard part to support this is already done. Just that we'd need someone who knows RAML well enough to help with writing the mapping layer.

**Comment by chengda** [comment]
I resolve the problem temparorily like this:
```
    @Bean
    @Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER)
    public ApiListingBuilderPlugin getApiPathEnrichPlugin() {
        return new ApiListingBuilderPlugin() {
            @Override
            public void apply(ApiListingContext apiListingContext) {
                List<ApiDescription> apis = apiListingContext.apiListingBuilder().build().getApis();
                ImmutableList.Builder builder = ImmutableList.builder();
                if (apis != null) {
                    apis.forEach(api -> {
                        builder.add(new ApiDescription(api.getGroupName().get(), api.getPath() + "?apiDescription=" + api.getDescription(), api.getDescription(), api.getOperations(), api.isHidden()));
                    });
                    apis = builder.build();
                    apiListingContext.apiListingBuilder().apis(apis);
                }
            }

            @Override
            public boolean supports(DocumentationType documentationType) {
                return true;
            }
        };
    }
```

**Comment by aburmeis** [comment]
As @dilipkrish mentioned this is not about content negotiation. If I have multiple mapped methods for a single GET /path with different parameters to distinguish betweeen the implementations. From API side they are all one endpoint. The operations should be merged (ServiceModelToSwagger2Mapper.mapOperations()) instead of overwrite each other. Currently only one mapping is documented, all others are dropped.

I am not clear how to handle different response types (from produces) here, at least all of them have to occur to produces. In the response I would expect kind of "any of" which may have to wait for OpenAPI 3 support.

**Comment by spyro2000** [comment]
Same problem here. 6 years later.

**Comment by RubenCiveira** [comment]
i use to have an endpoint with different operations on the value of some parameter. For example, /find?by=zip&search={zip} and /find?by=email&search={email} on that case, I change @chengda solution to append to the path the fixed part of the params. 

```
  @Bean
  @Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER)
  public ApiListingBuilderPlugin getApiPathEnrichPlugin() {
    return new ApiListingBuilderPlugin() {
      @Override
      public void apply(final ApiListingContext apiListingContext) {
        final ApiListing build = apiListingContext.apiListingBuilder().build();
        final List<ApiDescription> apis = build.getApis();
        if (apis != null) {
          apiListingContext.apiListingBuilder()
              .apis(apis.stream().map(SwaggerConfig.this::rename).collect(Collectors.toList()));
        }
      }

      @Override
      public boolean supports(final DocumentationType documentationType) {
        return true;
      }
    };
  }

  @SuppressWarnings("deprecation")
  private ApiDescription rename(ApiDescription api) {
    final List<Operation> operations = api.getOperations();
    final StringBuilder params = new StringBuilder();
    if (operations.size() == 1) {
      final Operation operation = operations.get(0);
      for (final Parameter parameter : operation.getParameters()) {
        final AllowableValues allowableValues = parameter.getAllowableValues();
        final List<String> options = allowableValues instanceof AllowableListValues
            ? ((AllowableListValues) allowableValues).getValues()
            : Arrays.asList();
        if (Boolean.TRUE.equals(parameter.isRequired()) && options.size() == 1) {
          params.append("&" + parameter.getName() + "=" + options.get(0));
        }
      }
    }
    return new ApiDescription(api.getGroupName().orElse(null),
        api.getPath() + (params.length() > 0 ? "?" + params.substring(1) : ""), api.getSummary(),
        api.getDescription(), api.getOperations(), api.isHidden());
  }
```

**Comment by chengda** [comment]
For new version of springfox,  I modified some codes,  it's like this:

```
    @Bean
    @Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER)
    public ApiListingBuilderPlugin apiListingBuilderPlugin() {
        return new ApiListingBuilderPlugin() {
            @Override
            public void apply(ApiListingContext apiListingContext) {
                List<ApiDescription> apis = apiListingContext.apiListingBuilder().build().getApis();
                ImmutableList.Builder<ApiDescription> builder = ImmutableList.builder();
                if (apis != null) {
                    apis.forEach(api -> builder.add(
                            new ApiDescription(
                                    api.getGroupName().get(),
                                    api.getPath() + "?_unique=" + api.getOperations().get(0).getUniqueId(),
                                    api.getSummary(),
                                    api.getDescription(),
                                    api.getOperations(),
                                    api.isHidden()
                            )));
                    apis = builder.build();
                    apiListingContext.apiListingBuilder().apis(apis);
                }
            }

            @Override
            public boolean supports(DocumentationType documentationType) {
                return true;
            }
        };
    }
````
It's  more generic than my previous solution.
