### ISSUE TITLE
@Api not working?

### ISSUE THREAD

**Issue by zonorion** [springfox/springfox#1143]
Hi all,
I use @Api(value = "Users", description = "User authorization") to change display on swagger, but it's not working.
Still display user-controller : User authorization.
How to resolve this problem?
Thanks.

**Comment by dilipkrish** [comment]
@zonorion The behavior of `@Api#value` changed in `springfox` 2.x. Swagger 2.0 introduced the notion of tags and In order to change the grouping you'd need need to use the `@Api#tags` attribute to change the grouping. 

like this `@Api(value = "Users", description = "User authorization", tags="Users") `

**Comment by zonorion** [comment]
Ok, thanks @dilipkrish  4 reply!
