### ISSUE TITLE
Supply the text values for `@ApiOperation, @ApiResponse, @ApiParam, @ApiModelProperty from an external resource file, instead of hardcoding?

### ISSUE THREAD

**Issue by joetconcur** [springfox/springfox#1180]
I want to supply the text values for `@ApiOperation`, `@ApiResponse`, `@ApiParam`, `@ApiModelProperty` from an external resource file, instead of hardcoding.

For example, say I have a file swaggerDocs.xml
```xml
<messages>
    <message id="my_api_name">My API</message>
    <message id="my_api_notes">This is my API</message>

</messages>
```

In the controller java, I want to be able to
```java
    @ApiOperation(value = "my_api_name", notes = "my_api_notes")
    
```
And springfox be able to translate the ids into text strings to be use in swagger json. 

Is there a way to achieve this?

Thanks.

**Comment by dilipkrish** [comment]
Absolutely. You could create a plugin to do just that.

**Comment by dilipkrish** [comment]
Here [is an example](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/schema/ApiModelPropertyPropertyBuilder.java) that you can use. Just make sure your plugin priority/order is after the swagger plugins have run.

**Comment by joetconcur** [comment]
Thanks so much for the quick answer. Are there documentation or more examples on this plugin creation? And once I created a new plugin class, how do I register/activate it?

**Comment by dilipkrish** [comment]
Any plugin or extensibility [is available here](https://github.com/springfox/springfox/tree/master/springfox-spi/src/main/java/springfox/documentation/spi). In the `spi` module, anything that ends in `*Plugin` is generally an extensibility point that is meant for library consumers to consume.

A recently implemented contribution was adding [support for bean validations](https://github.com/springfox/springfox/tree/master/springfox-bean-validators). Its fairly simple and small in scope and should give you an idea how one goes about doing it. Its a set of plugins are act on `ModelProperty`ies, hence they are  implementations of `ModelPropertyBuilderPlugin`.

The extensibility points available are:
- At the schema level
    - `ModelBuilderPlugin` for enriching models
    - `ModelPropertyBuilderPlugin` for enriching model properties
    - `TypeNameProviderPlugin` - these are for overriding names for models
- At the service level
    - `ApiListingBuilderPlugin` - for enriching api listings
    - `DefaultsProviderPlugin` - for providing your own defaults
    - `DocumentationPlugin` -  for enriching the documentation context
    - `ExpandedParameterBuilderPlugin` for parameter expansion used in the context of `@ModelAttribute`
    - `OperationBuilderPlugin` for enriching operations
    - `OperationModelsProviderPlugin` for providing additional models that you might load a different way 
    - `ParameterBuilderPlugin` - for enriching parameters

 Its not well documented other than javadocs of course :) So I'm laying it out here so that it can be incorporated into the docs.

These are the steps. The ___same___ patterns apply to all of the :point_up: extensibility mechanisms

1. Implement the plugin interface
2. Give the [plugin an order](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/parameter/ApiParamParameterBuilder.java#L42). In general spring plugins get the highest priority,  The swagger plugins (the ones that process all the `@Api...` annotations) layer information on top. So the order that you'd write will need to layer information at the end.
3. Each plugin has 
     - a [*context](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/parameter/ApiParamParameterBuilder.java#L47) and provides access to any information that the plugin might need to do its job
     - a [*builder](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/parameter/ApiParamParameterBuilder.java#L49) for the type of object that the plugin is intended to support for e.g. a `ModelPropertyBuilderPlugin` will have access to a `ModelPropertyBuilder`. This builder is what is used to build the model _after_ all the plugins have had access to contribute/enrich the underlying object.
4. Update any builder properties your plugin cares about
5. Register the plugin as a `@bean`, so that the plugin registry can pick it up.

Thats it!

So in your case you'd implement one of the plugins for e.g. 
1. an `ParameterBuilderPlugin` that can read the `@ApiParam` annotation
2. and take the `value` and use that as a key perhaps to read from your xml resource mapping (from messages) 
3. and [replace the name](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/parameter/ApiParamParameterBuilder.java#L54) [using the builder](https://github.com/springfox/springfox/blob/master/springfox-core/src/main/java/springfox/documentation/builders/ParameterBuilder.java#L79-L82).

Let me know if you have any questions.

**Comment by joetconcur** [comment]
Thanks so much for taking the time to explain in detail. I will try to digest all the information and will circle back if I have more questions.

**Comment by phillipuniverse** [comment]
@dilipkrish thanks a lot this helped a ton! Just to help contribute, it was really simple for me to translate the pieces of my API.

This is what my endpoint looks like:

<img width="841" alt="screen shot 2016-06-03 at 10 09 21 am" src="https://cloud.githubusercontent.com/assets/684275/15783319/4e33c3a4-2973-11e6-87ec-93d4d4a4ab31.png">

Then this is what I wrote to do the translation. I personally just put this as an inner class within the `@Configuration` class that has `@EnableSwagger2`:

```java
@Configuration
@EnableWebMvc
@EnableSwagger2
public class RestApiMvcConfiguration extends BroadleafRestApiMvcConfiguration {
    
    @Bean
    public Docket globalApi() {
        ...
    }

    @Bean
    public TranslationOperationBuilderPlugin translationPlugin() {
        return new TranslationOperationBuilderPlugin();
    }
    
    @Order(Ordered.LOWEST_PRECEDENCE)
    public static class TranslationOperationBuilderPlugin implements OperationBuilderPlugin {

        @Autowired
        protected MessageSource translator;
        
        @Override
        public boolean supports(DocumentationType delimiter) {
            return true;
        }

        @Override
        public void apply(OperationContext context) {
            Set<ResponseMessage> messages = context.operationBuilder().build().getResponseMessages();
            Set<ResponseMessage> translated = new HashSet<>();
            for (ResponseMessage untranslated : messages) {
                String translation = translator.getMessage(untranslated.getMessage(), null, untranslated.getMessage(), null);
                translated.add(new ResponseMessage(untranslated.getCode(),
                    translation,
                    untranslated.getResponseModel(),
                    untranslated.getHeaders()));
            }
            context.operationBuilder().responseMessages(translated);
        }
        
    }
}
```

This works GREAT and has the advantage of working with the normal Spring out-of-the-box message bundles! The one step further here would be to add locale selection but I'm not sure how that could work. The issue there is that you would want to differentiate a locale for every request, but all of the endpoint documentation is built at startup and then cached... so I'm not sure how that would work. But this definitely solves the externalization problem.

Thanks again for such a great library that supports extension so well!

**Comment by sac10nikam** [comment]
please send me running example. I would like to see actual configurations made and the xml file having error messages. The controller as well.

**Comment by dilipkrish** [comment]
@sac10nikam please see the [steps listed above](https://github.com/springfox/springfox/issues/1180#issuecomment-185523244) ☝️

**Comment by sac10nikam** [comment]
Created plugin to load properties from file but it didn't work.
Please share how to load properties file using plugin

**Comment by dilipkrish** [comment]
Your plugin needs to be something like this. Looks like you're not using the property reader you created

```java
    @Order(MY_PLUGIN_ORDER) //Replace with YOUR plugin order
    public static class ApiOperationBuilderPlugin implements OperationBuilderPlugin {

        @Autowired
        protected MessageSource translator;
        @Autowired
        ApiDescriptionPropertiesReader propReader;

        @Override
        public boolean supports(DocumentationType delimiter) {
            return true;
        }

        @Override
        public void apply(OperationContext context) {
            Set<ResponseMessage> messages = context.operationBuilder().build().getResponseMessages();
            Set<ResponseMessage> translated = new HashSet<ResponseMessage>();
            for (ResponseMessage untranslated : messages) {
                // NOT THIS String translation = translator.getMessage(untranslated.getMessage(), null, untranslated.getMessage(),
                        null);
                //But THIS
                String translation = propReader.getProperty(untranslated.getMessage());
                translated.add(new ResponseMessage(untranslated.getCode(), translation,
                        untranslated.getResponseModel(), untranslated.getHeaders()));
            }
            context.operationBuilder().responseMessages(translated);
        }

    }

}
```

**Comment by sac10nikam** [comment]
Thanks. I have used above code with @Order(Ordered.LOWEST_PRECEDENCE). Still its not working
I guess I am missing something? Can you please tell me. Urgent!!!

**Comment by sac10nikam** [comment]
Not sure What am I missing here now. Thanks for your time buddy

Now I am using EnvironmentConfig to load properties
@Service(value = "environmentConfig")
@Scope(value = "singleton")
@PropertySources
({
@PropertySource(value="classpath:/swagger-messages.properties",ignoreResourceNotFound=true)
})
public class EnvironmentConfig {

    private static final Logger LOGGER = LoggerFactory.getLogger(EnvironmentConfig.class);
    @Autowired
    private Environment environment;
    private static Environment env;

    @PostConstruct
    public void init() {
        env = environment;
    }

    public static String getProperty(String key) {
        LOGGER.debug("Getting property  :" + key);
        return env.getProperty(key);
    }
}

@Order(Ordered.LOWEST_PRECEDENCE) //Replace with YOUR plugin order
    public static class ApiOperationBuilderPlugin implements OperationBuilderPlugin {

        @Autowired
        protected MessageSource translator;
        @Autowired
        EnvironmentConfig propReader;

        @Override
        public boolean supports(DocumentationType delimiter) {
            return true;
        }

        @Override
        public void apply(OperationContext context) {
            Set<ResponseMessage> messages = context.operationBuilder().build().getResponseMessages();
            Set<ResponseMessage> translated = new HashSet<ResponseMessage>();
            for (ResponseMessage untranslated : messages) {
                // NOT THIS String translation = translator.getMessage(untranslated.getMessage(), null, untranslated.getMessage(), null);
                //But THIS
                String translation = propReader.getProperty(untranslated.getMessage());
                translated.add(new ResponseMessage(untranslated.getCode(), translation,
                        untranslated.getResponseModel(), untranslated.getHeaders()));
            }
            context.operationBuilder().responseMessages(translated);
        }

    }

**Comment by dilipkrish** [comment]
No idea, beyond this you'd have to debug and figure out whats going on

**Comment by sac10nikam** [comment]
ok ;(

**Comment by AmirhosseinBayat** [comment]
in this sample code you'd push [This](https://github.com/springfox/springfox/issues/1180#issuecomment-185489550), I used it but there is incompatible Optional<> with java.util optional and com.google.common.base.Optional.
what should I do?

**Comment by AmirhosseinBayat** [comment]
`import test`

**Comment by AmirhosseinBayat** [comment]
```
public class EnvironmentConfig {

    private static final Logger LOGGER = LoggerFactory.getLogger(EnvironmentConfig.class);
    @Autowired
    private Environment environment;
    private static Environment env;

    @PostConstruct
    public void init() {
        env = environment;
    }

    public static String getProperty(String key) {
        LOGGER.debug("Getting property  :" + key);
        return env.getProperty(key);
    }
}
```

**Comment by AmirhosseinBayat** [comment]
> public class EnvironmentConfig {
> 
>     private static final Logger LOGGER = LoggerFactory.getLogger(EnvironmentConfig.class);
>     @Autowired
>     private Environment environment;
>     private static Environment env;
> 
>     @PostConstruct
>     public void init() {
>         env = environment;
>     }
> 
>     public static String getProperty(String key) {
>         LOGGER.debug("Getting property  :" + key);
>         return env.getProperty(key);
>     }
> }

**Comment by divStar** [comment]
Thanks for the information so far, but what I am not really getting is how the `TranslationOperationBuilderPlugin` @phillipuniverse wrote is getting its MessageSource.

I have a XML-file similar to that of @sac10nikam, but I have troubles understanding how that file is supposed to be read in the first place as the MessageSource is autowired, but not explicitly defined.

I am also trying to understand how to create some sort of plugin, which reads strings from a XML-file since I do not want to keep it english-only, nor have a lot of hardcoded text describing service-methods and -attributes.
