### ISSUE TITLE
spring boot actuator support

### ISSUE THREAD

**Issue by tokuhirom** [springfox/springfox#1184]
I need spring boot actuator support for springfox.

Currently, I'm using dirty hack like the code in followng repo.
https://github.com/tokuhirom/springfox-springboot-actuator-demo

**Comment by dilipkrish** [comment]
Could you share a little bit of background on why you need to do this?

**Comment by tokuhirom** [comment]
I want to publish swagger2 data on
actuator port(I use another port to serve actuator). Because i can hide it
by firewall very easy.

I want to share the swagger schema with our frontend engineer team, but i
don't want publish the API spec to the world wide web.

**Comment by dilipkrish** [comment]
Makes sense this seems like a great idea :metal:

Couple of comments
- this library also supports vanilla spring-mvc 3.2.x onwards. So adding this to the core library might not be ideal.
- Without much evidence, just based on the issues reported. Anecdotally, it seems like the majority of people will not use it this way

However since you have a solution it would be awesome if you could create a module that might be useful for folks that might want to use it with actuator. 

Ideally your solution would include
- an annotation `@EnableSwagger2InActuator` 
- This annotation does the same kind of bean registration as the `@EnableSwagger2` does that makes the swagger related endpoints are available @ the actuator port.

Honestly, I don't have the bandwidth to maintain this on my own, but I'd be happy to use your help if you're willing to shepherd this and handle any support/issues that might come up. At the very least, i'll definitely link to your repository and direct folks your way!

:beers:

**Comment by tokuhirom** [comment]
I implemented it on my repo~ Could you review this?
https://github.com/tokuhirom/springfox-swagger2-actuator

**Comment by dilipkrish** [comment]
@tokuhirom thank you for taking time to do this! :bow:  

I'm wondering if I could perhaps make it easier for you by [extracting a the duplicated code or perhaps creating a public constructor so that it can be subclassed](https://github.com/tokuhirom/springfox-swagger2-actuator/blob/management-port-hack/springfox-swagger2-actuator/src/main/java/me/geso/swagger2_actuator/Swagger2MvcEndpoint.java#L30-L87). Do Also what is the use of [this method](https://github.com/tokuhirom/springfox-swagger2-actuator/blob/management-port-hack/springfox-swagger2-actuator/src/main/java/me/geso/swagger2_actuator/Swagger2Endpoint.java#L12-L15)?

Are you planning to release it on maven-central/jcentral? Also, would you like to me to fork this into the springfox organization and give you access to it? We could incubate it till you think its stable. Or would you prefer that I just link to your repo in the docs!?

**Comment by tokuhirom** [comment]
I want to release this library on maven central :)

My suggestion is following style:

Module | Packages
----------- | ----------------
springfox-swagger2-core | s.d.swagger2.configuration, s.d.swagger2.mappers( and common part in springfox.documentation.swagger2.web.)
springfox-swagger2 | s.d.swagger2.web, s.d.swagger2.annotations.EnableSwagger2
springfox-swagger2-actuator | s.d.swagger2.annotations.EnableSwagger2Actuator, s.d.swagger2.annotations.actuator

And include springfox-swagger2-actuator in main springfox repo.

**Comment by dilipkrish** [comment]
Don't follow what you're suggesting with the modules and packages? Could you explain?

**Comment by dilipkrish** [comment]
@tokuhirom ping!

**Comment by Hronom** [comment]
Any progress or workarounds ?

**Comment by dilipkrish** [comment]
@Hronom none other than looking at the awesome example @tokuhirom put together.

**Comment by kamilwlf** [comment]
Any progress or workarounds ?

**Comment by dilipkrish** [comment]
@kamilwlf see ☝️

**Comment by vmaleze** [comment]
For those of you who uses spring-boot-2, the hack is a bit more simple.
Create a new SwaggerConfiguration file to avoid the registration on the standard port (And do not use `@EnableSwagger2`) :
```java
@Configuration
@Import({SpringfoxWebMvcConfiguration.class}) 
@ComponentScan(basePackages = {
    "springfox.documentation.swagger2.readers.parameter",
    "springfox.documentation.swagger2.mappers"
})
public class SwaggerAutoConfiguration {

    @Bean
    public JacksonModuleRegistrar swagger2Module() {
        return new Swagger2JacksonModule();
    }
}
```

And the next thing is to copy the Swagger2Controller and make it a `@ContollerEndpoint` : 
```java
@Component
@ControllerEndpoint(id = "swagger2")
public class Swagger2Controller {

    private static final String DEFAULT_URL = "/v2/api-docs";
    private static final Logger LOGGER = LoggerFactory.getLogger(Swagger2Controller.class);
    private static final String HAL_MEDIA_TYPE = "application/hal+json";

    private final String hostNameOverride;
    private final DocumentationCache documentationCache;
    private final ServiceModelToSwagger2Mapper mapper;
    private final JsonSerializer jsonSerializer;

    public Swagger2Controller(Environment environment, DocumentationCache documentationCache,
        ServiceModelToSwagger2Mapper mapper, JsonSerializer jsonSerializer) {

        this.hostNameOverride =
            environment.getProperty(
                "springfox.documentation.swagger.v2.host",
                "DEFAULT");
        this.documentationCache = documentationCache;
        this.mapper = mapper;
        this.jsonSerializer = jsonSerializer;
    }

    @GetMapping(value = DEFAULT_URL, produces = {APPLICATION_JSON_VALUE, HAL_MEDIA_TYPE})
    @ResponseBody
    public ResponseEntity<Json> getDocumentation(
        @RequestParam(value = "group", required = false) String swaggerGroup,
        HttpServletRequest servletRequest) {

        String groupName = Optional.ofNullable(swaggerGroup).orElse(Docket.DEFAULT_GROUP_NAME);
        Documentation documentation = documentationCache.documentationByGroup(groupName);
        if (documentation == null) {
            LOGGER.warn("Unable to find specification for group {}", groupName);
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
        Swagger swagger = mapper.mapDocumentation(documentation);
        UriComponents uriComponents = componentsFrom(servletRequest, swagger.getBasePath());
        swagger.basePath(isNullOrEmpty(uriComponents.getPath()) ? "/" : uriComponents.getPath());
        if (isNullOrEmpty(swagger.getHost())) {
            swagger.host(hostName(uriComponents));
        }
        return new ResponseEntity<>(jsonSerializer.toJson(swagger), HttpStatus.OK);
    }

    private String hostName(UriComponents uriComponents) {
        if ("DEFAULT".equals(hostNameOverride)) {
            String host = uriComponents.getHost();
            int port = uriComponents.getPort();
            if (port > -1) {
                return String.format("%s:%d", host, port);
            }
            return host;
        }
        return hostNameOverride;
    }
}
```

Obviously if you want to transfer other controllers, you should be able to repeat the process.

The only thing a bit annoying is that I could not find a way to re-write the path as the HandleMapper maps the route to the standart port.

I will probably make a PR when Springfox is updated to spring-boot-2.0 as it is pretty easy to mix both config (Apart for re-writing the route part)

**Comment by dilipkrish** [comment]
Thank you @vmaleze! Spring boot 2 support should be there soon.

**Comment by amirbayan** [comment]
@vmaleze how can I access swagger-ui.html using your implementation? the json request is working but I cannot access the UI.

**Comment by tagerl** [comment]
Regarding your question @vmaleze, I was able to use a similar solution to what @vmaleze suggested also for ApiResourceController for the /swagger-resources api's.
Also since it is up on /actuator I added redirects for the 3 /swagger-resources api's & the /v2/api-docs api to /actuator/[original api].
