### ISSUE TITLE
How could publish this project to my own repo for reference

### ISSUE THREAD

**Issue by wxjlibra** [springfox/springfox#1185]
It's a not an issue. Instead, I'm asking for help.

I've forked a certain 2.3.0 release build to my own repo. And thing i want to do now is to build my fix on my forked branch. In order to do CI in our process. I need to publish the build once it's build to our own internal maven repo.
I'd like to see how I could achieve that? by modify some of the files? I've tried though, however, there seems to be many task dependencies and version strategy if clause which made me hard to realise that.
I've tried with 'maven publish' under the root path. however that succeed with all the tasks UP-TO-DATE. but nothing happens. I've also tried publish to local as a default task made by gradle and that worked(packages appears in .m2).
Hope you could give a hand. Really appreciate.

**Comment by dilipkrish** [comment]
Unless you have some proprietary modifications I would recommend just use the publicly published version because
- You will get future bug fixes pretty easily without having to rebuild
- You will not need to mess with a modified build 
- You may end up with a divergent fork that can never join back

you may be better served by just proxying your private repo to get it from maven central.

Anyways having said that, it may be easier to modifying the [publish target](https://github.com/springfox/springfox/blob/df604457fe59b258ef04e78ece0498d229c6f87c/buildSrc/src/main/groovy/springfox/gradlebuild/plugins/MultiProjectReleasePlugin.groovy#L145-L150) for you gradle builds to publish to your repository.

```bash
./gradlew snapshot -i -x check
# you may need to supply a bogus bintray userid/pwd, in which case you might use something like this
#./gradlew snapshot -PbintrayUsername=BOGUS -PbintrayPassword=BOGUS -i -x check
```

Keep in mind this will only publish snapshot versions.

**Comment by wxjlibra** [comment]
That's really been helpful. Great thanks!
