### ISSUE TITLE
Programmatically accessing controller API documentation

### ISSUE THREAD

**Issue by woemler** [springfox/springfox#1190]
**Can a controller access it's own Swagger documentation object/JSON?**

I would like to try to implement functionality in a controller whereby an `OPTIONS` request to a particular URL would then return JSON-formatted Swagger documentation for that particular URL or controller.  Presumably, the object that is serialized into the JSON at `/v2/api-docs` is accessible within the servlet context, and traversable.  Is their an API for this?

**Comment by dilipkrish** [comment]
Take a look at [InMemorySwaggerResourcesProvider.java](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/InMemorySwaggerResourcesProvider.java#L45) for an example. All the service models that are inferred are available in the `DocumentationCache` which is just a map of documentation by groups. 

Groups are a concept that is defined when defining a `Docket`. By default we create a docket with a "default" group. 

Now the missing part is providing a lookup for a method by "path" so that when you ask for the `OPTIONS` on the endpoint, it can do a lookup by path in the documentation cache. 

If you do build something like this it would be awesome get your contribution back because it will be super useful when building out support for `spring-data-rest` #238 .

**Comment by woemler** [comment]
Thanks for a response, I will take a look and then post again when I have made some progress.
