### ISSUE TITLE
Add Native Support For guava and JDK 8 Optionals

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#1199]

**Comment by raderio** [comment]
`Optional<Boolean> data`
in swagger is
```
"data": {
    "present": true
  }
```
but should be
```
"data": true
```
How to fix this?

**Comment by dilipkrish** [comment]
Your ObjectMapper doesnt match with the one that's configured with springfox. If you're using jackson and java 8 you need the jackson java 8 module.

**Comment by foal** [comment]
It can be also because of the `springfox.documentation.spi.service.contexts.Defaults` register `java.util.Optional` as general class (non WildcardType). So the rule doesn't match the model property.

To correct it add to Doclet configuration custom rule (pay attention to the types!!!)
```java
AlternateTypeRules.newRule(typeResolver.resolve(java.util.Optional.class, springfox.documentation.schema.WildcardType.class), springfox.documentation.schema.WildcardType.class)
```

something like this
```java
@Autowired
private TypeResolver typeResolver;

@Bean
public Docket swaggerDocket() {
  final Docket docket = new Docket(DocumentationType.SWAGGER_2)
    .select()
       .apis(RequestHandlerSelectors.any())
       .paths(PathSelectors.any())
    .build()
    .alternateTypeRules(AlternateTypeRules.newRule(typeResolver.resolve(Optional.class, WildcardType.class), WildcardType.class))
    .useDefaultResponseMessages(false);
    return docket;
}

```
