### ISSUE TITLE
CachingModelPropertiesProvider - NullPointerException

### ISSUE THREAD

**Issue by bharatkaushik** [springfox/springfox#1207]
I am using the following spring cloud starter project - spring-cloud-starter-parent:Brixton.M5
I have enabled FeignClient and enabled Swagger2. 
I had come across an issue when both Swagger and Feign client were enabled together. Based on the inputs given here -  https://github.com/springfox/springfox/issues/1074#issuecomment-161551409 , I have adopted the latest springfox version (2.4) and I was able to get past that issue. 

The following is an example of an API in my controller:
```
@ApiOperation(value = "Get University by PK", notes = "Get Universtity based on PK.", response= SampleDTO.class)
@ApiResponses(value = { @ApiResponse(code = 404, message = "University not found") })
@RequestMapping(value = "/university/{pk}", produces = { MediaType.APPLICATION_JSON_VALUE }, method = RequestMethod.GET)
public ResponseEntity<EntityMap> getUniversity(Context context,
           @ApiParam(value = "University PK", required = true) @PathVariable String pk,
           @ApiParam(value = "Template Name", required = false) @RequestParam(required = false) String templateName)
   {
       /*
       *Code comes here
      */
   }
```
The SampleDTO is annotated with an @ApiModel annoation.
When I run my spring boot application, I see the following message in my logs

> 7:06:40.017 [main] WARN  s.d.s.p.CachingModelPropertiesProvider - Exception calculating properties for model(com.manh.cp.fw.sample.university.client.dto.SampleDTO) -> ModelContext{type=com.manh.cp.fw.sample.university.client.dto.SampleDTO, isReturnType=true}. java.lang.NullPointerException

And the Swagger UI has not generated any model schema. 

Can you please let me know if this is an issue or if I am missing anything. 

Thanks!

**Comment by dilipkrish** [comment]
@bharatkaushik Since I'm not super familiar with spring-cloud and feign. Would you mind creating and sharing the smallest possible setup that reproduces this bug. It sounds like this is going to be a common request and and I'd like to address it. However I do not have the time to _learn_ spring cloud etc. to do that.

**Comment by bharatkaushik** [comment]
I am attaching my list of gradle dependencies and also my Application File. Let me know if that's sufficient
[ApplicationDependencies.zip](https://github.com/springfox/springfox/files/161542/ApplicationDependencies.zip)

**Comment by dilipkrish** [comment]
@bharatkaushik not really, since I can just download it and build/run as-is. I'd need the models etc. so that I can get the same NPE that you're getting in your environment.

Preferably sharing a github repo will be better than via zip files.

**Comment by bharatkaushik** [comment]
I will try uploading it tomorrow. Also, is there a way to see the whole stack trace?

**Comment by praveen12bnitt** [comment]
@dilipkrish here is a sample app which reproduces the issues.
https://github.com/praveen12bnitt/springfox-gh1207-issue

Start the app and you will see the below error messages.

```
2016-03-17 20:17:37.303  WARN 2832 --- [           main] s.d.s.p.CachingModelPropertiesProvider   : Exception calculating properties for model(com.github.prajan.dto.UniversityDTO) -> ModelContext{type=com.github.prajan.dto.UniversityDTO, isReturnType=true}. java.lang.NullPointerException
2016-03-17 20:17:37.311  WARN 2832 --- [           main] s.d.s.p.CachingModelPropertiesProvider   : Exception calculating properties for model(com.github.prajan.dto.UniversityDTO) -> ModelContext{type=com.github.prajan.dto.UniversityDTO, isReturnType=true}. java.lang.NullPointerException
2016-03-17 20:17:37.312  WARN 2832 --- [           main] s.d.s.p.CachingModelPropertiesProvider   : Exception calculating properties for model(com.github.prajan.dto.UniversityDTO) -> ModelContext{type=com.github.prajan.dto.UniversityDTO, isReturnType=false}. java.lang.NullPointerException
2016-03-17 20:17:37.312  WARN 2832 --- [           main] s.d.s.p.CachingModelPropertiesProvider   : Exception calculating properties for model(com.github.prajan.dto.UniversityDTO) -> ModelContext{type=com.github.prajan.dto.UniversityDTO, isReturnType=false}. java.lang.NullPointerException
```

What i found was, the NPE is coming for springfox.documentation.schema.property.OptimizedModelPropertiesProvider because the objectMapper is null. 

When a Feign client is added to the application, spring-cloud creates a child application context for feign beans. Check org.springframework.cloud.context.named.NamedContextFactory for details on how they create the context. Once this context is refreshed, it signals a ContextRefreshedEvent which is picked up by DocumentationPluginsBootstrapper.  The problem is the main application context initialization is still not complete.  RequestMappingHandlerAdapter is not even created at this time and so ObjectMapperConfigurer does not fire ObjectMapperConfigured. This is the reason why OptimizedModelPropertiesProvider  has a null object mapper.

When it RequestMappingHandlerAdapter is created at a later time, all the events are fired, but its too late. DocumentationPluginsBootstrapper has already finished its model evaluation.

**Comment by praveen12bnitt** [comment]
Here is where the [refresh event](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/context/named/NamedContextFactory.java#L109) is published from the child application context.

**Comment by dilipkrish** [comment]
Thanks for creating the issue and explaining the problem as well. 🤘🏻I'll take a look and see how we might address this issue

**Comment by praveen12bnitt** [comment]
I was thinking if we can check `contextRefreshedEvent`'s application context and proceed with `DocumentationPluginsBootstrapper` initialization only if its the root context.

```java
if(contextRefreshedEvent.getApplicationContext().getRoot() != null) {
    // Not the root context. So skip this event.
} else {
    if (initialized.compareAndSet(false, true)) {
        // proceed with processing.
    }
}
```
What do you think?

**Comment by dilipkrish** [comment]
I'd agree. I arrived at the same solution. Would you like to submit a PR?

**Comment by praveen12bnitt** [comment]
Done sir!

**Comment by praveen12bnitt** [comment]
@dilipkrish Is there a way to use snapshot version in our project? and what is tentative date for 2.5.0 release?

**Comment by dilipkrish** [comment]
2.5 is set for June. But there might be a 2.4.1 earlier if there are critical bugs or there are sufficient number of fixes to warrant a patch release. 

About the snapshot version, have you seen the [dependencies section](http://springfox.github.io/springfox/docs/current/#dependencies)?

**Comment by fsudrot** [comment]
In fact with a SpringBoot Brixton.M5, your correction just disable the swagger ui with a message "fetching resource list: null; Please wait.". There is no ContextRefreshedEvent generated with a null parent.
I just work around the problem with a diffrent check : 
```
        if (contextRefreshedEvent.getApplicationContext().getParent().getParent() != null) {
            log.info("contextRefreshedEvent {} not from root application context. So skipping this event.", contextRefreshedEvent);
        }
```
instead of 
```
        if(contextRefreshedEvent.getApplicationContext().getParent() != null) {
            log.info("contextRefreshedEvent {} not from root application context. So skipping this event.", contextRefreshedEvent);
        }
```

It works for me but the fix is ugly.

I've attached the test project with the "fixed" class.

Have you any suggestion ?
[test-springfox.zip](https://github.com/springfox/springfox/files/187817/test-springfox.zip)

**Comment by dilipkrish** [comment]
Thanks for reporting this issue. Reopening...

**Comment by praveen12bnitt** [comment]
Looks like I missed something.. Let me find a cleaner solution.

**Comment by praveen12bnitt** [comment]
How about making `DocumentationPluginsBootstrapper` implement [SmartInitializingSingleton](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/beans/factory/SmartInitializingSingleton.html).  Here is something interesting from the javadoc.

This callback variant is somewhat similar to ContextRefreshedEvent but doesn't require an implementation of ApplicationListener, **with no need to filter context references across a context hierarchy etc**. It also implies a more minimal dependency on just the beans package and is being honored by standalone ListableBeanFactory implementations, not just in an ApplicationContext environment.

I will give it a try, In the meantime, can you let me know what you think ?

**Comment by dilipkrish** [comment]
Only catch is that it's a spring 4.1+ construct. Perhaps with some clever conditional beans it could work but it would be a breaking change otherwise

**Comment by dilipkrish** [comment]
I believe the solution is to use the `SmartLifeCycle` instead of handling `ContextRefeshed` event in an application event listener.  It doesn't break current behavior.

@fsudrot @praveen12bnitt would you mind checking if [this implementation](https://github.com/springfox/springfox/pull/1239) works

**Comment by praveen12bnitt** [comment]
I got your latest change.Do you have a way to install the jar in maven local cache, so that i can test this change ?

**Comment by dilipkrish** [comment]
Not really I don't want to pull it in just yet. Since Im not very familiar with spring-cloud and its band of merry men I was hoping one of you could see if it works locally using the same trick that @fsudrot applied by re-defining the `DocumentationBootstrapper` bean using the implementation from the PR above. Or you could get the latest source and build from source using the following command. and use the snapshot

```bash
#build and publish to maven local
./gradlew clean build pTML
```

If you're having trouble let me know

**Comment by praveen12bnitt** [comment]
I can confirm you that the fix you added using `SmartLifeCycle` works in my test app, which is using spring-cloud.

**Comment by fsudrot** [comment]
It works fine for me too, even in my "real" application.

**Comment by dilipkrish** [comment]
:+1: thanks for confirming @praveen12bnitt and @fsudrot

**Comment by praveen12bnitt** [comment]
Can you make this fix available in master, so that i can start using snapshot version in our project?

**Comment by dilipkrish** [comment]
@praveen12bnitt sorry it too so long. Have been busy with my day job. Check it out and let me know.

**Comment by praveen12bnitt** [comment]
No problems. Thank you..

**Comment by tjuchniewicz** [comment]
It works fine for me too using 2.4.1-SNAPSHOT.

**Comment by cvw643** [comment]
I meet the same issue.
