### ISSUE TITLE
Inconsistent attributes for adding description to the API

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#1228]
Version 2.4.0

Current naming scheme for adding a description to the documentation:
@ApiOperation: value
@ApiModel: description // value used for alternative name for the model
@ApiModelProperty: value
@ApiParam: value

IMHO the "description" attribute should be always used for the description of an Operation/Model/ModelProperty.

**Comment by dilipkrish** [comment]
Just FYI, we are using the swagger core annotations. So much of this inconsistency stems from there.

- [@ApiOperation description is from the value](http://docs.swagger.io/swagger-core/current/apidocs/io/swagger/annotations/ApiOperation.html#value())
- [@ApiModelProperty description is from the value](http://docs.swagger.io/swagger-core/current/apidocs/io/swagger/annotations/ApiModelProperty.html#value())
- [@ApiParam description is from the value](http://docs.swagger.io/swagger-core/current/apidocs/io/swagger/annotations/ApiParam.html#value())
- [@ApiModel has a description property](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/schema/ApiModelBuilder.java#L49-L51)

Since we don't control this and its in a dependent library, this will not be fixed
