### ISSUE TITLE
Fields not visible from children when implementing interfaces in parent request objects

### ISSUE THREAD

**Issue by stashthecode** [springfox/springfox#1258]
- [x] Am using springfox version 2.4.0 ( latest release )

- [x] The following small test shows that implementation of the interface SwaggerBugIF in request object SwaggerBugRequest somehow makes the fields in the subclassed object 
SwaggerBugExtended invisible. ( remove "implements SwaggerBugIF" and the field in SwaggerBugExtended becomes visible )  

Am trying to move away from the spring implementation from mangofactory ( where this works ) to allign with some other projects..

[springProblem.txt](https://github.com/springfox/springfox/files/216161/springProblem.txt)
![swaggerbugui](https://cloud.githubusercontent.com/assets/18429938/14479064/5419ccd0-011b-11e6-868d-ea4252a1b897.png)

**Comment by dilipkrish** [comment]
Thanks for reporting the bug is in the [comparison on the methods](https://github.com/springfox/springfox/blob/master/springfox-schema/src/main/java/springfox/documentation/schema/property/OptimizedModelPropertiesProvider.java#L321-L327). When we introduce the interface, the equality comparison is no longer correct.
