### ISSUE TITLE
Make the URL paths of swagger-ui and the other resources configurable

### ISSUE THREAD

**Issue by mibeumer** [springfox/springfox#1263]
Release: 2.4.0

Feature Request:

We have the requirement, that path should be configurable under which the resources should be accessible. The paths should be in a special area underneath /api/rest/swagger/. (for example: http://localhost:8080/application/api/rest/swagger/swagger-ui.html and http://localhost:8080/application/api/rest/swagger/api-docs)

I speak about:
- /configuration/security
- /configuration/ui
- /swagger-resource
- /swagger-ui
- the webjar artifacts.
- /api-docs

I already search the issues and read the documentation and find no suitable solution. The resources and swagger-ui.html must not be reacheable underneath the old paths, so a rewrite is no solution for me. But perhaps I have overlooked a solution.

Kind Regards
mibeumer

**Comment by dilipkrish** [comment]
Couple of things to get out of the way

Url | New Url in 2.4.+| Purpose
------------ | ------------- | ------------- 
/configuration/security | /swagger-resources/configuration/security | Configuring swagger-ui security
/configuration/ui | /swagger-resources/configuration/ui | Configuring swagger-ui options

Since swagger ui is a static resource it needs to rely on *known* endpoints to configure itself at runtime. So these ☝️  are ***cool uris** that cannot change.

Regarding [where swagger-ui itself is served](http://springfox.github.io/springfox/docs/current/#q13) and [where the api docs are served](http://springfox.github.io/springfox/docs/current/#customizing-the-swagger-endpoints) those are totally configurable.

**Comment by mibeumer** [comment]
Maybe I don't get it. So in the future the resources are at /swagger-resources/. But I need them at api/rest/swagger/swagger-resources/.

So I thougth it would be possible to make the Resources configurable with the property placeholder. So to put an additional @RequestMapping with the default value (/) to the ApiResourceController and the Swagger2Controller.

Code-Snippet:
`@RequestMapping(value = "${springfox.documentation.swagger.resources.base.path:/}
public class ApiResourceController {`

Code-Snippet:
`@RequestMapping(value = "${springfox.documentation.swagger.swagger2.base.path:/}
public class Swagger2Controller {`

So It can set
`springfox.documentation.swagger.resources.base.path=/api/rest/swagger/
springfox.documentation.swagger.swagger2.base.path=/api/rest/swagger/`

In the springContext.xml:
`< resources mapping="/api/rest/swagger/**" location="classpath:/META-INF/resources/"/ >`


I also can provide a pull request.

But you have to decide, if this is for the pupose of this project. It would be very nice for me and I also think for others.

By the way I use spring-mvc and I don't use spring-boot.

**Comment by dilipkrish** [comment]
@mibeumer The is issue is not about how to configure it via property files, [we already do this](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L69-L70) for the api-docs. 

The issue is we have [static java script bundled in swagger-ui](https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/js/springfox.js#L7-L15) that relies on this information to work. 

`ApiResourceController` is a meta-controller if you will. Just to re-iterate you're free to configure where the api-docs are served from (see [the links in the docs](https://github.com/springfox/springfox/issues/1263#issuecomment-210839308) ☝️for more information on that). So the `ApiResourceController` is a ***known*** endpoint where the swagger-ui can ask for meta information about the url for the api-docs.

Hope that makes sense.

**Comment by aditi-goel** [comment]
@dilipkrish My @Path is not picking by swagger. when i am using @RestControoler it is working but when i am using @Path it is not working. Can you please help me

**Comment by dilipkrish** [comment]
JAX-RS annotations are not supported. Also please dont comment on closed issues, especially if they are unrelated. Feel free to open new issues with more details
