### ISSUE TITLE
defaultValue is ignored in @PathVariable @ApiParam(defaultValue = "0") Long id 

### ISSUE THREAD

**Issue by vijayansrinivasan** [springfox/springfox#1304]
defaultValue is ignored in @PathVariable @ApiParam(defaultValue = "0") Long id 

Working in springfox-swagger2: 2.2.2

Not working in springfox-swagger2: 2.4.0

**Comment by dilipkrish** [comment]
@vijayansrinivasan Could you create [a failing test](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/test/groovy/springfox/documentation/swagger/readers/parameter/ApiParamParameterBuilderSpec.groovy). It appears that [it should work](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/parameter/ApiParamParameterBuilder.java#L57).

**Comment by dilipkrish** [comment]
@vijayansrinivasan ping!

**Comment by vijayansrinivasan** [comment]
Sorry for late response, I requested my team member to reproduce the issue, Give us 2 more days, If not reproduced, We will close it.

**Comment by pgomulka** [comment]
I have exactly the same problem.
` public Collection<Integer> getAll(@ApiParam(value = "skip first... ", required = false, defaultValue = "0") @RequestParam Integer offset,
                                       @ApiParam(value = "Limit ...", required = false, defaultValue = "100") @RequestParam Integer limit) `

problem occurs when upgrading from 2.2.2 (works on this one) to any higher version.
When you change defaultValue to any value different then 0 it works.

**Comment by vijayansrinivasan** [comment]
@pogumulka thanks for the hint that it works for non 0 default values

**Comment by pgomulka** [comment]
ok almost certainly it was due to jackson bug : https://github.com/FasterXML/jackson-databind/issues/849
I was using 2.6.2, when upgraded to 2.7.2 problem does not occur any more.
@vijayansrinivasan could you please confirm your jackson version?

**Comment by dilipkrish** [comment]
Thanks for getting to the bottom of that @pgomulka!

**Comment by nsaxena** [comment]
@pgomulka I am commenting on behalf of @vijayansrinivasan. Our jackson version is 2.6.6 and when I updated it to 2.7.4 the issue was resolved. Thanks for the helpful tip!

**Comment by pgomulka** [comment]
no problem. I had to stick with this problem anyway. 
Jackson 2.7 fixes the problem with default values, but it has a different behavior for superclass generics. See: AbstractJackson2HttpMessageConverter.readInternal
There is an issue raised in jackson github now: https://github.com/FasterXML/jackson-databind/issues/1087
and here it is explained in change log: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.7#fix-generic-type-resolution-mechanism

According to spring community -  https://jira.spring.io/browse/SPR-13728 - this will be fixed in Spring 4. There is no release date yet (as far as I am aware)

**Comment by nsaxena** [comment]
Thanks for the update @pgomulka; will look into this issue in our project.
