### ISSUE TITLE
Appends 80 to hostname - Deployed in Cloud Foundry

### ISSUE THREAD

**Issue by vivekshankar03** [springfox/springfox#1378]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using?  2.0.2

What kind of issue is this? This is same issues as - https://github.com/springfox/springfox/issues/1278. I have deployed my application to pivotal cloud foundry,

**Comment by dilipkrish** [comment]
First off, please upgrade to 2.5.0. This is an issue with the proxy headers I believe. Since I don't run stuff on pivotal cloud foundry I wouldn't know much about how its configured. So I can't help u much other than provide you with hints on what might be happening based on info you give me.

My guess is that PCF isn't url rewriting correctly or configured incorrectly.

**Comment by vivekshankar03** [comment]
Thanks , I  will upgrade and provide an update.

**Comment by vivekshankar03** [comment]
I updated to 2.5.0 and still facing the same issue. When I use http endpoint I don't see port 80 getting appended to hostname. But when I use https endpoint , I see port 80 getting appended.

**Comment by dilipkrish** [comment]
What do the api-docs look like. Does it give you a basePath? Is there a way you can configure clouldfoundry? I know its possible because the jhipster guys do it
