### ISSUE TITLE
Getting around CSRF in swagger-ui

### ISSUE THREAD

**Issue by hogancr** [springfox/springfox#1450]
Please take the time to search the repository, if your question has already been asked or answered.

- [ 2.5] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [ Question] Question. Is this a question about how to do a certain thing? 

I have a spring MVC project and I'm securing it with spring security and using Springfox to get swagger-ui based documentation. Everything works great except for CSRF failures when I try to access PUT, POST APIs through the swagger UI. If I disable csrf then it works fine for all APIs. (It will sometimes redirect me to the login page, but one I am logged in I can access all of the apis fine on the Swagger UI page.

I've been all over the web looking for a resolution and most of them involve changing the swagger-ui page to add code for processing the CSRF headers, which I'd like to avoid.  

One thing I've noticed is that alot of the issues here that mention CSRF at all (just searching the forum) don't really address this because they are putting csrf.disable() in their config.

So I'm left to wonder, is there no good workaround and people are doing this just so they can use swagger in their spring project? This seems like bad security policy. Right now, unless I can find another solution I'm thinking of having separate configuration XMLs for deployment and development environments, and turning CSRF on only for deployment so that I can still use swagger to test my APIs in the dev/integration stage. Is this the only solution, or is there some kind of configuration I can apply to get swagger-ui to process CSRF correctly?

I apologize if I've overlooked something in the documentation but it doesn't seem to answer that question directly from what I've seen.

**Comment by dilipkrish** [comment]
@hogancr Not really sure what the problem would be. Are you using swagger-ui served from a different server than your api-docs?

**Comment by pveeramachineni** [comment]
I ran into the same exact scenario with one of my projects. I think the problem is that the CSRF token is not passed back in the header with any of the requests. Spring Security expects the token  in the request header which it compares against the token in a cookie or some other persistence mechanism that can be configured. Spring also allows customizing the name of the token.

**Comment by hogancr** [comment]
Yes, I've been discussing this with a colleague recently and can give you a slightly more coherent explanation of what's going on now that I understand it better. Sorry for the delay, I was also on vacation for a few days. 

The issue is that when you log in, spring security sends back a token in a customizable header as pveeramachineni said. This is meant to protect against CSRF attacks in which 1) your website defines the session ID in a cookie which your browser stores, then 2) other malicious sites can link to, say, PUT http://yoursite.com/somethingDangerous, and the session cookie will get sent automatically by the browser because it is for your site. The solution is to block requests that don't contain the CSRF token in a header, because these headers are not transmitted automatically like cookies are. It will mostly affect everything but GET requests since the assumption is that a GET request will not modify user state and is therefore "safe."

This processing is enabled by default in spring security with login form authentication. There's a few ways to get around this flow, but they all involve using a different security configuration that doesn't always make sense. Two ways we talked about were
1) you can transmit the session token in a header rather than a cookie, but that still requires you in your client code to capture that header value that comes back when you log in and send it back manually in the header with each request, so it is ultimately the same as the CSRF flow and will thus fail when using swagger UI if it isn't designed to do this. A way around it would be to add a field to the page where they can manually enter the token value, but that's a little hacky, or to add a login widget in the swagger UI page, that will submit a login and get the token back, but that could turn into a rabbit hole too because there may be alot of different ways to implement such login behavior for different server systems...I'm not really well versed enough to say if that's advisable or not.
2) you can add a sessionless mode for using the APIs, where you transmit the username and password in every request and no session is created. This is probably the approach we will take since our primary purpose for using swagger is for third party apps to interact with our APIs and that flow kind of makes sense for the app developers anyway because they are accepting the login credentials anyway (which doesn't always make sense in a third party app situation but does for our case) and using a sessionless API also decouples them from the session lifecycle on the server side.

At any rate, for situations where this doesn't exactly make sense it might be nice to have a way to capture the CSRF token and send it with requests, since I get the impression this is not an uncommon way to handle this type of attack. The token is not a fixed value between logins though so hard coding it as a global header value wouldn't make sense. The spring security docs explain how to implement client-side code that won't get caught by the CSRF filter if you are interested. http://docs.spring.io/spring-security/site/docs/current/reference/html/csrf.html#csrf-include-csrf-token

I think we're good for our application but others might benefit from being able to run swagger UI with CSRF enabled. Thanks for your quick reply!

**Comment by krunal-thakur** [comment]
Any reason why this was closed?
When CSRF protection is enabled in Spring, Swagger UI fails on anything other than GET. 

This is because X-CSRFToken is not passed as a part of header

**Comment by dilipkrish** [comment]
Can't you selectively ignore CSRF for resources? In any case, I think its an issue for [swagger-ui](https://github.com/swagger-api/swagger-ui). Its provided as a webjar as a convenience for the simple use cases.

**Comment by krunal-thakur** [comment]
CSRF token is validated by spring so I can not selectively ignore it. Even though swagger-ui is provided as webjar it provides a way to add custom header

swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("Authorization", "XXXX", "header"));

Need to add code in swagger-fox which can read cookie and pass that as a header  parameter with every request

**Comment by dilipkrish** [comment]
That is not in scope for springfox. I think you should check with the [swagger-ui team](https://github.com/swagger-api/swagger-ui).

**Comment by krunal-thakur** [comment]
spring-UI already has a capability to add header parameters. If you can provide some way to send back CSRF token as part of SecurityConfiguration then everything should work fine.

I am currently using below workaround for changing value returned by ApiResourceController -> securityConfiguration()

[SwaggerSecurityResponseModifier.txt](https://github.com/springfox/springfox/files/727653/SwaggerSecurityResponseModifier.txt)

Here I have defined Controller Advice to access CSRF Token from cookie and then populate into apiKeyValue.

Also you need to define following bean wherever swagger is configured

@Bean
	  SecurityConfiguration security() {    	 
		    
	    return new SecurityConfiguration(
	        "test-app-client-id",
	        "test-app-client-secret",
	        "test-app-realm",
	        "test-app",
	        "{{X-XSRF-COOKIE}}",
	        ApiKeyVehicle.HEADER, 
	        "X-XSRF-TOKEN", 
	        "," /*scope separator*/);
	  }

**Comment by evser** [comment]
@dilipkrish , I don't understand, why you've closed it?
Could you include krunal-thakur solution as part of your library??

Because this issue is not solved.

**Comment by edeandrea** [comment]
The solution @krunal-thakur proposes *only* works if you have HTTP sessions with session-affinity turned on for your REST API. This is because the initial GET will create the CSRF token and store it in session.

It also depends on what type of [CSRF defense you are implementing](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#CSRF_Specific_Defense).

If your API is stateless, then every GET request gets a new token (if the browser doesn't send one in).

**Comment by krunal-thakur** [comment]
@edeandrea My solution should work even if it is Stateless as I am extracting CSRF token from HttpServletRequest and not from session. Also this solution was just to make sure that we are able to pass CSRF token when we do post from swagger.

**Comment by edeandrea** [comment]
@krunal-thakur No it doesn't work when configured with Spring Security's [`CookieCsrfTokenRepository`](https://github.com/spring-projects/spring-security/blob/4.2.3.RELEASE/web/src/main/java/org/springframework/security/web/csrf/CookieCsrfTokenRepository.java) in that case & here's why.

The `ResponseBodyAdvice` class for the `SecurityConfiguration` endpoint is only called *once* when swagger-ui loads its ui. Even navigating around within swagger-ui (expanding/collapsing sections/etc) triggers new GET calls which don't re-run the `SecurityConfiguration` endpoint. The minute it issues a new GET then it breaks because Spring Security's `CsrfFilter` when used in conjunction with `CookieCsrfTokenRepository` issues a new CSRF token (see [`CookieCsrfTokenRepository.loadToken`](https://github.com/spring-projects/spring-security/blob/4.2.3.RELEASE/web/src/main/java/org/springframework/security/web/csrf/CookieCsrfTokenRepository.java#L97_L100)) whenever one can not be read via a cookie. The swagger-ui "try it" feature does not send the CSRF token in via a cookie, so the response contains a new cookie which over-writes what is set on the browser, therefore subsequent PUT/POST/DELETE operations fail.

**Comment by krunal-thakur** [comment]
@edeandrea  I am using CookieCsrfTokenRepository to generate csrf token, but i have set it to [`CookieCsrfTokenRepository.withHttpOnlyFalse()`](https://github.com/spring-projects/spring-security/blob/4.2.3.RELEASE/web/src/main/java/org/springframework/security/web/csrf/CookieCsrfTokenRepository.java#L169) so that it is accessible to java script. This way token does not change on subsequent request.

**Comment by edeandrea** [comment]
@krunal-thakur Then it has to do with the fact I am also using authentication. As part of the authentication process [`CsrfAuthenticationStrategy.onAuthentication`](https://github.com/spring-projects/spring-security/blob/4.2.3.RELEASE/web/src/main/java/org/springframework/security/web/csrf/CsrfAuthenticationStrategy.java#L56_L69) kicks in & generates a new CSRF token. Unfortunately the `SecurityConfiguration` has already been read at that point.

If authentication is not turned on then yes your solution works, so I guess I mis-stated my original post when saying it only works for stateless applications & re-state it as *it only works when there is no authentication*.

**Comment by P8H** [comment]
I think I found a suitable workaround. I am deactivated the CSRF protection for _swagger-ui.html_ and check if the _Referer_ in the request header is right.

```
@Override
protected void configure(HttpSecurity http) throws Exception {
  http
    ...
        .and()
        .csrf().requireCsrfProtectionMatcher(
           new NegatedRequestMatcher(new OrRequestMatcher(
              new RequestHeaderRequestMatcher("Referer", "http://localhost:8080/v2/swagger-ui.html"),
              new AntPathRequestMatcher("/swagger-ui.html"),
              new AntPathRequestMatcher("/login") // GET only path
                                ))
         );
```

In my understanding it doesn't weak the CSRF protection because the _Referer_ attribute gets validate.
See also: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Checking_the_Referer_Header

The disadvantage is that the hostname has to be known at init time and that all request methods (like GET) get also secured by CSRF token which is not standard conform.

**Comment by katelfox** [comment]
What release is this scheduled for and when will that release be out?

**Comment by dilipkrish** [comment]
@katelfox finishing up with a couple of bugs... this week.

**Comment by ahoehma** [comment]
one comment to @mnoky  .... http://localhost:8080/swagger-ui.html is not always the right string to check I guess. For example if one run a spring-boot with different port or different context-path.
Right?

**Comment by mnoky** [comment]
@ahoehma Right, YMMV. In my case I only run swagger UI locally in development mode. The important thing to note is that you shouldn't just blindly disable CSRF if the referer matches "yoursite/swagger-ui.html". Otherwise, a malicious user could disable CSRF for ANY PAGE by simply setting the referer appropriately!

**Comment by atoztoa** [comment]
https://github.com/springfox/springfox/pull/2434

**Comment by bmistry13** [comment]
Hi All,

I have the following use case where the CSRF token is changing with EACH API CALL (POST/PUT/DELETE)?

We store CSRF token in a cookie where javascript can read from cookie and send as value as HEADER  X-CSRF-TOKEN with each REST call.  Is there any way to customize the behavior of fetching value for CSRF token or call /csrf API before calling each and every CRUD (PUT/POST/DELETE/PATCH) APIs.

Swagger-doc is hosted with the same server with REST API.  

Currently, only the first call works which fetch token from /csrf api  (Since token changed it does not work for a subsequent request unless refresh whole page).

Any idea, how to make it work with token changing since the initial fetch request?
