### ISSUE TITLE
For for example

### ISSUE THREAD

**Issue by davidnewcomb** [springfox/springfox#1487]
Latest example:
https://springfox.github.io/springfox/docs/current/

When you write the following:
> Give the plugin an order **for e.g.** ApiParamParameterBuilder has an order specified..

what you are actually saying is:
> Give the plugin an order **for for example** ApiParamParameterBuilder has an order specified..

http://www.dictionary.com/browse/e-g

While this might appear to be minor it is very irritating because screen readers break the abbreviation down and read it as **for for example**. This breaks the flow of the reading so that you think here is an error and you are distracted away from hearing the next bit. ...and it's bad English!

Please change all references to correct English, e.g

> Give the plugin an order e.g. ApiParamParameterBuilder has an order specified..

**Comment by dilipkrish** [comment]
Im sorry its annoying. However it would be super helpful for [folks like you to fix them](https://github.com/springfox/springfox/blob/master/docs/asciidoc/extensibility.adoc) as you identify these problems. Its no different than bugs, its obviously not intentional to trip people (or screen readers) up.

**Comment by davidnewcomb** [comment]
Ok, look out for my pull request!

**Comment by dilipkrish** [comment]
Closing this for now in preparation for the release
