### ISSUE TITLE
Reflection access from context objects

### ISSUE THREAD

**Issue by ry4n-sc0tt** [springfox/springfox#1624]
In the version 2.6.1 (currently the latest version), it is no longer possible to access the relevant reflection object from the relevant context objects. For example, when writing a custom `OperationBuilderPlugin` in version 2.5.0, I could get the appropriate `java.lang.reflect.Method` from the `OperationContext` by calling `context.getHandlerMethod().getMethod();` but I no longer see any way to accomplish this.

Assuming you don't want to prevent developers from writing custom plugins that require access to reflection-based objects like this, I can see 3 options:
* Add back `getHandlerMethod()` and similar methods to various context objects for full backward-compatibility (I assume you had a reason for removing the method in the first place, so I don't expect this will be a viable option)
* Add a method to the context object to access the reflection object directly, like `OperationContext.getReflectionMethod()`
* Add some kind of mechanism for developers to provide their own implementation of context objects

Depending on the approach, I would be happy to work on this and submit a pull request.

**Comment by dilipkrish** [comment]
Would be good to know what your use case is? It was removed (should've been deprecated, but was an oversight) because we don't want to expose the internals of how we get the parameter types and return types. There are methods to access annotations on the method etc. but that is still internal to the context.

The reason for this change is to accommodate different paradigms of services other than spring-mvc. For e.g. to enable `spring-data-rest` or `grails` we don't want to rely on an operation being backed by a `HandlerMethod`.

**Comment by ry4n-sc0tt** [comment]
Some of the reader plugins I have written read the javadoc comments and use those in the swagger documentation. For example, the comment text from the javadoc method documentation is used for the operation notes. To make this work, I need access to the underlying `java.lang.reflect....` object.

Is the second option above (Add a method to the context object to access the reflection object directly) acceptable? It doesn't make any assumptions about spring-mvc, spring-data-rest, grails, or any other framework.

**Comment by dilipkrish** [comment]
How is access to the method reflectively letting you read javadocs? The preferred approach is to use annotations.

**Comment by ry4n-sc0tt** [comment]
In the same way that we don't want to duplicate information by requiring both the `@RequestMapping` and `@ApiOperation` to document the HTTP method, we don't want to duplicate information in the javadoc and the various `@Api...` annotations (since we use javadocs for additional documentation). By having a single source of truth, we run less risk of one getting updated without the other.

**Comment by dilipkrish** [comment]
Right.. my question is how are you accessing javadocs at runtime using reflection. Im not aware of a way to do that.

**Comment by dilipkrish** [comment]
How are you identifying the javadoc on the server given a method ... pseudo code?

**Comment by ry4n-sc0tt** [comment]
The serialized java object created by the custom doclet stores the javadoc comments in maps, where the key is the fully-qualified signature of the method (class, field, etc).

```
getMethodDocumentation(Method method)
{
  String signature = getSignature(method); // massage the method signature to match javadoc naming
  return methodDocs.get(qualifiedName);
}
```

**Comment by ry4n-sc0tt** [comment]
Did that answer your question?

**Comment by dilipkrish** [comment]
Yeah it did. Still trying to solve the problem without exposing the `HandlerMethod`. Im wondering if we can solve this problem by adding an annotation say something like this

```java
/***
* Your javadoc goes here 
***/
@JavadocKey("unique-uuid")
@RequestMapping ("/some-api-endpoint", method = GET)
public ResponseEntity<Entity> someMethod() {
...
}
...
```

If you can use the documentation key to store the javadocs by your uuid in the annotation. Then you could easily write a plugin to use the documentation key.

**Comment by ry4n-sc0tt** [comment]
Actually, I'd prefer to expose the `java.lang.reflect.Method` (et al) directly, rather than the `HandlerMethod`, similar to how annotations are now exposed directly. That is what I meant by the second option in the initial issue description.

**Comment by dilipkrish** [comment]
Everywhere, if not already removed, direct references to an operation's resolution to a method have been deprecated. Im hesitant to expose the internals, because what would the method that exposes the `java.lang.reflect.Method` do in cases where that is not a valid concept (grails/spring-data-rest). 

We already have a notion of key in `RequestHandlerKey` which uniquely represents an operation. Do you think you could work with that, I'd have no problems exposing that in the operation.

**Comment by ry4n-sc0tt** [comment]
Unfortunately, `RequestHandlerKey` does not contain enough information to uniquely identify a method, and even if it did, I don't know how I would translate that to what's available in the doclet.

Forgive my ignorance, but if there is no underlying `java.lang.reflect.Method` in grails and spring-data-rest, where do the annotations come from?

**Comment by dilipkrish** [comment]
They are usually [synthesized](https://github.com/springfox/springfox/blob/master/springfox-data-rest/src/main/java/springfox/documentation/spring/data/rest/SynthesizedAnnotations.java#L32-L42) so that the machinery that needs these annotations don't have to change nor know where the come from. Annotations are really just treated as hints not really predicated on being on a method or a class. 

The basic currency of swagger or any service description language is endpoints which have url, media types supported, or produced, and inputs and responses. Different frameworks implement it differently. For e.g. the plan is to support JAX-RS services too, and it does not have a notion of RequestMappings with handler methods. So I really don't want to expose a `Method` and have every other implementation return null except spring-mvc. That is anathema to good [SOLID principles](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) in software development.

Also, there is a simple work around for doing this like I [suggested above](https://github.com/springfox/springfox/issues/1624#issuecomment-270686689). Your pseudocode will still work.

```java
getMethodDocumentation(Method method)
{
  String javadocKey = getJavadocKey(method); // massage the method signature to match javadoc naming
  return methodDocs.get(javadocKey);
}
```

The only change you'd need to make is to allow your method docs to be stored using custom keys. 

Not trying to be hard, but as a library we need to be careful about what we expose, because for the most part I end up supporting it for the rest of eternity.

**Comment by ry4n-sc0tt** [comment]
Another option would be to expose the `RequestHandler` in the `OperationContext` (via the `RequestMappingContext`), and expose the `Method` as an `Optional<ResolvedMethod>` in the `RequestHandler`. Is that any better?

**Comment by ry4n-sc0tt** [comment]
Drat, that last option only solves one use case -- it doesn't solve the issue for method parameters (I have a similar custom `ParameterBuilderPlugin`). If exposing an `Optional<ResolvedMethod>` in the `RequestHandler` isn't acceptable, we would probably have to expose the `RequestHandler` in the `RequestMappingContext`, and expose a `protected` method to create each `OperationContext` in `ApiOperationReader`. This would allow me to create custom `OperationContext` and `ResolvedMethodParameter` objects to expose the information I need.

Ultimately, I am trying hard to avoid anything that requires changes to be made in the controller code (like the proposed annotation workaround), as I am maintaining my own (internal) open source project, and don't have any direct control over the projects that consume it.

**Comment by ry4n-sc0tt** [comment]
@dilipkrish - Any thoughts on this approach? The changes to the springfox project seem pretty minimal...

**Comment by ry4n-sc0tt** [comment]
In case anyone else has a similar issue, I solved this by overriding `WebMvcRequestHandler.getName()` to return the fully-qualified name of the method, and using that to look up the javadoc information. I already had a custom `OperationBuilderPlugin` that sets the `summary` to something more readable, so this change did not affect the swagger UI.

**Comment by piglingcn** [comment]
what about this? https://gitee.com/largerfish/swagger-doc

**Comment by walec51** [comment]
I want to add some operations description based on the interfaces the handler implements.
Besides the above there are many other cases when you would want to add information based on other things then annotations on the handler. Removing getHandlerMethod was just ignorant and forces us to use annotation with redundant information...

**Comment by dilipkrish** [comment]
You know you can use something like `@Description` annotation and create your own plugin to read that right?
