### ISSUE TITLE
@ApiModel strange behaviour when giving an existing class as the value string

### ISSUE THREAD

**Issue by fpanovski** [springfox/springfox#1674]
Hello,

While using version 2.6.1 I ran into a peculiar issue. I have backend model classes that I would like to limit to internal-use only. For this reason, I have API models that contain the backend model as a private member variable, and expose only the fields I wish to expose using public getters and `@JsonProperty`. This looks as follows:

    ApiModel(value = "Address")
    public class AddressResource {
    private Address address; // internal model class

    SingleAddressResource(Address address) {
        this.address = address;
    }

    @JsonProperty("addressUuid")
    @ApiModelProperty(value = "The Address UUID")
    public UUID getAddressUUID() {
        return address.addressUUID;
    }

The problem here is that if the value string is set to something that is *not* a class name (e.g. `AddressObject`), it works as I wish it to and it renders correctly on the Swagger UI page. 

However, if as above, the string is a class that exists (`Address`), it takes the fields from the class (in my case, the internal only class). This then exposes fields I do not wish exposes.

The `@ApiModel` comments on `value()` say the following:

    Provide an alternative name for the model. By default, the class name is used.

Which to my mind sounds different from the actual behaviour I describe above (as it is more than just an alternative name - it inspects the class of that name if it exists!).

Is the description of the `value()` function wrong, or is this a bug?

**Comment by MaksimOrlov** [comment]
Hello, @fpanovski 

I guess, SpringFox see your private **Address** model, may be you have a _getter_ somewhere...

Could you provide a whole source listing and output of the Swagger UI page ?

You've got such a situation because of model _merging_.
For now, if you have two different models, but with same names, SpringFox will merge it in to one model.
Otherwise, unfortunately, there is no way, to introduce two models in the api listing with same names.

There is a PR #1671, that can fix it. According to the PR, you will get two models one with 'original_name' and one with 'original_name_1', so, your listing will be correct.

To fix that now you should add class Address to ignorable types, or just add 

@ApiModelProperty(hidden = true) on private Address address

**Comment by dilipkrish** [comment]
@fpanovski While you are correct that that is the intent of the value object. We use it to override the type name of the class that represents. So if it finds a model in the model definitions with that class name it will use that definition. 

We deviate from the intent of the annotations sometimes to preserve the spirit of this library, which is to only use the annotations for hints to help the inference of models and types be better.

If you will notice the type inference in this library is much superior to the generics support provided by swagger-core. So while its useful in swagger-core, which relies on this metadata via annotations, in this library it is only to provide hints to make it better.
