### ISSUE TITLE
X-Forwarded-Port NumberFormatException: For input string: "443,443"

### ISSUE THREAD

**Issue by sixcorners** [springfox/springfox#1706]
```stacktrace
    java.lang.NumberFormatException: For input string: "443,443"
    	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    	at java.lang.Integer.parseInt(Integer.java:580)
    	at java.lang.Integer.parseInt(Integer.java:615)
    	at springfox.documentation.swagger2.web.HostNameProvider.componentsFrom(HostNameProvider.java:72)
```
Is "443,443" a value that is supposed to be in "X-Forwarded-Port" in the first place?

**Comment by dilipkrish** [comment]
Looks like the header is getting set incorrectly. No sure what is doing that

**Comment by emas80** [comment]
Hi, we are having the same exact issue reaching swagger-ui from our Api Gateway, except that is "80,80" for us.

This started to happen after we upgraded Spring Cloud and Spring Boot on our Api Gateway that uses Zuul.

We see that the headers forwarded by the gateway are

"x-forwarded-proto":"https,http"
"x-forwarded-port":"80,80"
"x-forwarded-for":"XXX.XXX.XXX.XXX, XXX.XXX.XXX.XXX, XXX.XXX.XXX.XXX"

If it can help, our current setup where Swagger does not work involves an Api Gateway using Spring Boot 1.4.4 and Spring Cloud CAMDEN.SR5, and the application(s) where Swagger is configured (and that is giving error) is behind the Api Gateway, and it uses Springfox Swagger 2.5.0 (the problem happens also with 2.6.1).
Both the Api Gateway and the swagger-enabled application runs on Kubernetes, and the swagger ui is reached by calling Ingress, that redirects to the Api Gateway, that redirects to the application in the end.

The problem started when we upgraded our Api Gateway Spring Boot version from 1.3.8.RELEASE, and spring-cloud-netflix from 1.1.7.RELEASE, everything was ok on Kubernetes before. 
We think the new version of Spring Cloud adds (correctly?) the forward port, while before it did not add it.

Please note that on another setup not involving Kubernetes the issue is not present. 
If we have an ELB in front of the Api Gateway and then again the swagger-enabled application (both Api Gateway and the application running on normal EC2 instances - no kubernetes no docker just a good old Tomcat), then everything still works, with the old and with the new Spring Boot/Spring Cloud versions.

**Comment by dilipkrish** [comment]
Thanks for reporting. A PR to fix this would be awesome!

**Comment by demaniak** [comment]
A little bit extra info - I just struck this problem when doing something slightly weird: basically I'm running Spring Boot zuul locally. I have a route setup that forwards to a another Zuul instance, behind which is the swagger ui and json I'm trying to access.

I thought at first that it was because I'm doing something extra-ordinarily silly, but it seems I am not alone :)

Does any body have any references for "valid-ish"  `x-forwarded-port` formats?

Stack trace for completeness:

```
[Request processing failed; nested exception is java.lang.NumberFormatException: For input string: "8088,80"] with root cause
java.lang.NumberFormatException: For input string: "8088,80"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at springfox.documentation.swagger2.web.HostNameProvider.componentsFrom(HostNameProvider.java:72)
	at springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(Swagger2Controller.java:84)
```

**Comment by demaniak** [comment]
@dilipkrish am I right in saying this:

1. It seems that `x-forwarded-port` is (or can be) a list of ports, which occurs if multiple reverse proxies are involve with a request. So each hop appends it's port to the list
2. `HostNameProvider` actually only needs the first port in such a list, since it is building up a URL that should be accessible from outside that first proxy.

If that seems reasonable, I can maybe try cooking up a PR.

**Comment by dilipkrish** [comment]
That is reasonable, thank you for looking into it... fixing it as we speak however.  There are a bunch of [other issues](https://github.com/springfox/springfox/issues?q=is%3Aissue+is%3Aopen+label%3Alooking-for-contributions) I could use help with.

**Comment by demaniak** [comment]
Shot, I will take a look at the issues, maybe there is actually something I can contribute to ;)
