### ISSUE TITLE
Un-deploying war using springfox-swagger-ui often fails

### ISSUE THREAD

**Issue by dhoffer** [springfox/springfox#1720]
I'm using springfox-swagger-ui version 2.6.1 in a few Spring boot wars deployed to Tomcat 7.x.  I'm deploying as standard wars to Tomcat not using Spring Boot's embedded Tomcat.  

When we undeploy the wars from Tomcat using the Manager app they often fail to undeploy.  This does not happen all the time but probably 50% of the time.

When I investigate the cause of the failure I find its always the same cause, the undeploy fails to remove the springfox-swagger-ui jar from the web app.  E.g. the springfox-swagger-ui jar is still in the lib folder and it can't be deleted by Tomcat.  My only workaround is to have to log into the VM and stop the Tomcat service and manually delete the springfox-swagger-ui jar.

My experience is that this is probably caused by a resource leak/lock in springfox-swagger-ui.  E.g. a stream was opened that was not properly closed.  

In a somewhat related note, when is the next release planned?  Ideally we would like to see this fixed in a new version even if there are no new features as the workaround is very time consuming and not all developers have access to the VM.

**Comment by dilipkrish** [comment]
@dhoffer thanks for reporting. Tomcat is notorious for its leaking resources, especially tomcat 7.  You don't have to use the swagger-ui that is bundled with this library as a webjar. You can pull in your own copy of swagger-ui and copy it into the web app and serve it as static content. See if thats fixes your problem.

Unfortunately this problem is really not in scope for this library.
