### ISSUE TITLE
Swagger methods in multiple groups being renamed

### ISSUE THREAD

**Issue by nitin02** [springfox/springfox#1724]
Using the latest version 2.6.1.

Ideally, I was using the swagger json generated to make API calls with the **swagger-js client** library. This was using the "**default**" group name (no group was specified).

I had a use-case to produce separate swagger JSONs for web and mobile platforms. So, I add a group, "**mobile**" for only a specific APIs.

On doing this, the common swagger methods (which were mapped in both groups) renamed the **operationId** to have a suffix of _1 or is sometimes showing the original method name. This behavior is erratic and not stable.

For example, if the method name was **getPets**, the swagger json (for either groups) sometimes produced **getPetsUsingGET** and sometimes **getPetsUsingGET_1** randomly.

Manually fixing the **operationId** does not solve the issue,

Like, **@ApiOperation(value = "", nickname = "getPetsUsingGET")**

The behavior is still erratic. Please fix this issue.

**Comment by dilipkrish** [comment]
It is supposed to generate consistent naming. Otherwise we'd [contract](https://github.com/springfox/springfox/blob/master/swagger-contract-tests/src/test/resources/contract/swagger2/declaration-feature-demonstration-service.json#L34)  [tests](https://github.com/springfox/springfox/blob/master/swagger-contract-tests/src/test/resources/contract/swagger2/declaration-feature-demonstration-service-codeGen.json#L34) failing all the time.

**Comment by nitin02** [comment]
The behavior we see, is either of getPetsUsingGET / getPetsUsingGET_1 and not getPetsUsingGET_1 and getPetsUsingGET_2.

**Comment by dilipkrish** [comment]
That is by design.
