### ISSUE TITLE
Status of support for v3.0.2 of swagger UI

### ISSUE THREAD

**Issue by JLLeitschuh** [springfox/springfox#1729]
I know that the new version of the swagger UI came out yesterday. I'm wondering if there is development effort behind supporting it? What is the status of such development?

Really nice job on this project. Really solid project.

https://github.com/swagger-api/swagger-ui

**Comment by dilipkrish** [comment]
@JLLeitschuh Thank you! means a lot! Would you be interested in taking a stab at porting the new version?

**Comment by JLLeitschuh** [comment]
I've got a lot of other projects on my plate. Deadline to ship a piece of software.

We can use the current version for the time being.

**Comment by shaqq** [comment]
Swagger UI 3 should be able to support the latest version of Swagger JSON.

The only change needed is instantiating the page here:

https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/src/web/js/springfox.js

**Comment by shaqq** [comment]
Alternatively, we could allow users of Springfox to set the `swaggerUiVersion` and add the html/js themselves, starting from a standard template.

This my preference because Swagger UI 3 is a React app that has hooks to add custom plugins, and it was built to support that. Although, this is understandably a much bigger undertaking than just changing the file I linked earlier and adding a route.

**Comment by dilipkrish** [comment]
Would be awesome to get a PR for this. Thank you for looking at it @shaqq
