### ISSUE TITLE
Spring Data Rest: Support for RepositoryPropertyReferenceController /{repository}/{id}/{property}

### ISSUE THREAD

**Issue by imduffy15** [springfox/springfox#1736]
Thanks for the fantastic work on the data-rest module.

I'm not seeing it export resources generated by the RepositoryPropertyReferenceController. This comes into play when a oneToMany resource extents on a model.

They appear at /{repository}/{id}/{property}

**Comment by dilipkrish** [comment]
Thank you for compliment. This is the big payoff in doing OSS work :)

Yeah those were left out, the thought being that we only document the aggregate roots. And the rest will follow via hypermedia controls. The addition of spring data rest support was a little hurried. Which is why Im taking some time to do a better job before 2.7 is released. If more people ask for it will definitely consider it for the next release.

**Comment by dilipkrish** [comment]
This has been implemented as part of #1623
