### ISSUE TITLE
Enum toString() vs. name()

### ISSUE THREAD

**Issue by tyutyutyu** [springfox/springfox#1745]
Springfox is using the Enum.toString() to get the enum's value instead of the Enum.name(). I think this is not correct because the Enum.name() returns ["the exact name, which will not vary from release to release"](https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html#name--)

Version: 2.6.1

**Comment by dilipkrish** [comment]
This is going by the documentation which says 
> ***Most programmers should use the toString() method in preference to this one, as the toString method may return a more user-friendly name.***. This will be a breaking change and I don't want to introduce this so late in the game when Im trying to release 2.7.0

**Comment by jonatan-ivanov** [comment]
@dilipkrish Are you planning to fix this in a later release?
Do you happen to have any workaround for this? I'm not able to modify the toString.

**Comment by dilipkrish** [comment]
@jonatan-ivanov There is #1991 that should make it extensible

**Comment by jonatan-ivanov** [comment]
@dilipkrish Could you please help me to understand how this PR can workaround the issue?

I still feel that the proper fix for this would be sending the name instead of toString (because that is what identifies the enum toString does not). However, in the drop-down, swagger-ui can show the toString (user-friendly name) but as the value, it should use the name (identifier).

**Comment by dilipkrish** [comment]
@jonatan-ivanov We just need to make sure that it is addressed, so can we create a new issue so that it is tracked?

**Comment by jonatan-ivanov** [comment]
@dilipkrish How about this: #2247
