### ISSUE TITLE
swagger-ui.html not available in when caching of static resources disabled in dev mode

### ISSUE THREAD

**Issue by kgignatyev-inspur** [springfox/springfox#1840]
In a way it is similar to #1460

Everything works fine when I am using default (prod) profile for application, however in development mode I would like to prevent static resources from being cached and want to see changes the moment I made them. So, in application-dev.properties file I specify

spring.resources.static-locations=file://${user.dir}/src/main/resources/static/
spring.resources.cache-period=0
endpoints.sensitive=false 

Then swagger-ui.html become unavailable which is inconvenient.

Is there a way to continue serving swagger-ui.html while disabling caching for static resources?

**Comment by dilipkrish** [comment]
Its not serving it because you explicitly told it not to serve it. Not because of caching

`spring.resources.static-locations=file://${user.dir}/src/main/resources/static/` is incorrect. It overrides the default behavior to only serve files in that location. So the swagger-ui web jar will be ignored.
