### ISSUE TITLE
Adding /login endpoint to documentation

### ISSUE THREAD

**Issue by vatri** [springfox/springfox#1892]
Hi.

I added Swagger and it generated my docs correctly. But I have /login endpoint which I want to document as well. It is the Spring Security default endpoint that means I don't have any controller in my package for it.

I am looking for solution for 2 days without success. I actually find this http://springfox.github.io/springfox/docs/current/#example-apilistingscannerplugin but it doesn't work as expected. 

Problems:

1. How to replace "default" as controller name to something else?

2. How to filter out error controller. Before implementing above plugin, following solution worked well.

```
new Docket()........paths(paths())

...

    private Predicate<String> paths() {
        return or(
                regex("/login.*"),
                regex("/product.*"),
                regex("/group.*"),
                regex("/order.*"),
//                regex("/cart.*"),
//                regex("/springsRestController.*"),
                regex("/cart.*"));
    }


```

Check attached image and you will understand my problems.

Any hint, suggestion or solution?

Thanks for help.
![screenshot_2017_06_29_12_49_45](https://user-images.githubusercontent.com/1230120/27684257-84348800-5cc9-11e7-87d0-dd7310004975.png)

**Comment by daithiscully** [comment]
Hey, I haven't used Spring security with Swagger yet so I don't think I can help you with replacing "default" as controller but might be able to help you with removing the basic error controller.
This is how I did it. You can select only the controllers found in your packages like so:
`
new Docket(DocumentationType.SWAGGER_2)
        .select()
        .apis(RequestHandlerSelectors.basePackage("com.example.controllersPackage"))
        .paths(PathSelectors.any())
        .build()
`
This removed the basic error controller from my Swagger UI/file. Hope this helped, good luck, have fun.

**Comment by vatri** [comment]
Hi David.

As you can see I already added paths filter and it worked. But then I've added filter and it doesn't work anymore. 

I tried with  RequestHandlerSelectors.basePackage("net.vatri.ecommerce.controllers") but doesn't help. Problem is in the filter which obviously overrides my config.

Here is full source of Swagger Config: https://pastebin.com/YvggY2Pc

**Comment by vatri** [comment]
P.S.

thanks for help anyway! I appreciate your effort!

**Comment by dilipkrish** [comment]
@vatri for *2* you can filter out the package the basic error controller belongs too, in this case it is `org.springframework.boot`. Regarding how to remove `default`, add tags to your operation and it will put the operations under that given tag.

**Comment by vatri** [comment]
Thanks for reply.

How can I filter out by package? And why filtering by URL doesn't work **anymore**? Are you sure it will work as you suggest?

2. I am not sure what is the operation and what are tags? Can you point me to some Readme, guide or reference?

Best,

**Comment by dilipkrish** [comment]
> How can I filter out by package? 
By filtering (**exclude**) the right package `Predicates.not(RequestHandlerSelectors.basePackage("<package-of-the -controller>"))` without the not its going to __only__ include the specified package.

> And why filtering by URL doesn't work anymore? 
it does you just have to specify the right ant matching regular expression

> Are you sure it will work as you suggest?
yest

**Comment by vatri** [comment]
@dilipkrish I don't understand you. 

But I am trying use your code:

```
        Predicate apis = Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.boot"));
        
        Docket docket = new Docket(DocumentationType.SWAGGER_2)
                .select()
//                .apis(RequestHandlerSelectors.any())
                .apis(apis)
//                .paths(PathSelectors.any())
                .paths(paths())
                .build();
```

But I still get error-controller. As I said, it seems my ApiListingScannerPlugin overwrites this filter. The .paths() had worked before I implemented the plugin. Following code worked (see above how this method is being called):

```
     private Predicate<String> paths() {
        return or(
                regex("/login.*"),
                regex("/product.*"),
                regex("/group.*"),
                regex("/order.*"),
//                regex("/cart.*"),
//                regex("/springsRestController.*"),
                regex("/cart.*"));
    }
```

> "it does you just have to specify the right ant matching regular expression"

What is ant-matching-regular-expression ? As I said, above filter/method had worked until I added the plugin.

**Comment by dilipkrish** [comment]
Not sure. It should work.

**Comment by vatri** [comment]
:)

There is (Maven) project in my Github (Ecommerce REST API....) so your or some good man could check and help what I would appreciate a lot.

**Comment by almasry** [comment]
this shitty error of the basic-error-controller  showing in the documentation doesn't seem to be fixable ! 

I followed all the possible solutions in a previous ticket https://github.com/springfox/springfox/issues/631, yet this seems unsolvable. Nothing works at all.

**Comment by dilipkrish** [comment]
@vatri sorry I didnt realize you meant [this repository](https://github.com/vatri/spring-rest-ecommerce). I'll take a look and let you know.

@AnilKumarReddyBelum I'll see what I can find. However, if its standard authentication mechanism like oauth, basic auth or api key then implicitly that is your documentation.

**Comment by simplyi** [comment]
@dilipkrish do you know any documentation or example that demonstrates how to use SpringFox to document the /login url provided by Spring Security?

I use Spring Boot with Spring Security and all my RESTful Web Service endpoints required an Authorization header(JWT) to be provided. To get the Authorization header value(JWT), user first needs to login. The /login is provided by Spring Security. Once user successfully logs in, Authorization header will be returned. So my Swagger UI Documentation needs to document the /login URL which is provided by Spring Security. I cannot find any documentation on how to document the provided by Spring Security /login endpoint. 

Are you aware of any? Can you advise? 

The only solution I was able to use these days is to simply create my own /login endpoint and provide SpringFox annotations for it do document Request and Response details. And when Swagger UI is used to send a /login request, Spring Security overrides the request and it works. Which is great. So my own /login endpoint is a kind of Fake login which only serves the documentation purpose. Since Spring Security overwrites it, the code inside of my own, fake /login never gets triggered, which is great and which is what I want. But I wondered how it is properly done with SpringFox? How to use SpringFox to document the /login Web Service Endpoint provided by Spring Security?

**Comment by FlasH-RUS** [comment]
@simplyi, we've just had the same requirement to document Spring's /oauth/* endpoints. Eventually a custom [ApiListingScannerPlugin](https://springfox.github.io/springfox/docs/current/#example-apilistingscannerplugin) plugin worked as in [the example](https://github.com/springfox/springfox/blob/master/swagger-contract-tests/src/main/java/springfox/test/contract/swagger/Bug1767ListingScanner.java) - just added the `@Component` and `@Order(SwaggerPluginSupport.SWAGGER_PLUGIN_ORDER)`. Note that the group you provide to `ApiDescription` is NOT the group from your `Docket` (i.e. it's not the one in drop-down at right top page corner), so by default your ApiDescriptions will appead in every Docket you have under "defaut" section.
In order to change the section name you need to provide a tag (surprise, surprise!) for `OperationBuilder` inside your `ApiDescription`. And I don't know what `ApiDescription` group is then...

**Comment by Syndlex** [comment]
@FlasH-RUS  I also need this. Do you have done this?
