### ISSUE TITLE
@JsonUnwrappred being ignored by Schema generation 

### ISSUE THREAD

**Issue by zootalures** [springfox/springfox#192]
This is as much a question of "should this work?" as a possible issue : 

We've got a bean with @JsonUnwrapped (this is using spring-hateos to provide ResourceSupport but I don't think that's important) 

```
public class CustomerResource extends ResourceSupport {
       public FetchedCustomerDetails getCustomerDetails() {
        return customerDetails;
       }
       public void setCustomerDetails(FetchedCustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
       }
       @JsonUnwrapped
       private FetchedCustomerDetails customerDetails;
 }
```

It seems that the schema generated doesn't take this into account: 

```
CustomerResource {
link (List[Link], optional),
customerDetails (FetchedCustomerDetails, optional)
}
FetchedCustomerDetails {
id (string, optional),
email (string, optional),
merchantRef (string, optional),
defaultCurrency (string, optional),
dob (string, optional),
billingAddress (PostalAddress, optional),
displayName (string, optional),
telephone (string, optional)
}
```

Is that the expected behaviour?  (It's quite a complex app config so it's possible that we've screwed up something else somewhere else). 

What I'd expect is  to see the types collapsed into one JSON schema element: 

```
CustomerResource {
link (List[Link], optional),
id (string, optional),
email (string, optional),
merchantRef (string, optional),
defaultCurrency (string, optional),
dob (string, optional),
billingAddress (PostalAddress, optional),
displayName (string, optional),
telephone (string, optional)
}
```

We're using Swagger 0.6.6, Spring MVC 3.2.6 and Jackson 2.3.0

The ObjectMapper has the JAXB extensibility module and JodaTime module plugged into it.

**Comment by paulalex** [comment]
iS this resolved as I am having the same issue in <springfox.version>2.6.1</springfox.version> and it looks like it shouldnt be the case.

I have an object which should be flattened into its parent but this object is in the swagger file and the swagger-codegen generated stubs expect the structure to include, this ends up with a generated pice of json which is not expected by jackson because it still has the extra object in it

**Comment by dilipkrish** [comment]
It should be resolved. Unless you're trying to do the same with a non-request/response body model.

**Comment by paulalex** [comment]
I read another post by you this morning and in fact to get this working I had to annotate both the getter and setter for the property with @JsonUnwrapped, it didnt work with the property annotated or just the getter annotated. Annotating both getter and setter I do end up with the extra class being generated by code gen, but I dont need to use it because the parent class has all the properties of the class flattened into it and the setter for the property is now on the parent class. Thanks.

**Comment by dilipkrish** [comment]
@paulalex  Could you perhaps create a new issue and provide an example or a breaking test. This is a very old issue on a version thats not even supported
