### ISSUE TITLE
ApiModelProperty defaults, custom metadata and more

### ISSUE THREAD

**Issue by pamput** [springfox/springfox#1923]
Hi!

Our team has been integrating with swagger using springfox for a while and we find it a really useful tool, especially the plugin compartment is making our lives good and allows us to do some crazy stuff reasonably easily :D

Unfortunately there are a couple of bits and bobs that are not supported by the current version of springfox, some of which are:

- It's not possible to set a default value for an ApiModelProperty (actually several fields are taken out compared to the swagger 2 specs)
- It would be nice to be able to add custom metadata to parameter objects

We are fiddling with the idea of forking the project and implementing these features ourselves, but we also wonder if it would be possible for you to implement these requirements if sponsored by us.

We have sponsored/paid a couple of open source projects to add features which would ideally go back to the main trunk of the project. We are not interested in IP ownership or having our logo on your page or any junk like that. We would just like the feature added :)

Let me know if this is something you would be interested in doing?

If possible please contact me at lukasz[at]billforward[dot]net.

**Comment by dilipkrish** [comment]
> It's not possible to set a default value for an ApiModelProperty (actually several fields are taken out compared to the swagger 2 specs)

Its not taken out as much as its not been asked for since its evolution from swagger 1.2 So if you do find something that is missing, would love to create issues for it.

> It would be nice to be able to add custom metadata to parameter objects

I believe parameters now support vendor extensions to allow customization.

I don't believe making both of your observations involves considerable effort. I'd be happy to incorporate them and better still would love PRs for them.

> We are fiddling with the idea of forking the project and implementing these features ourselves, but we also wonder if it would be possible for you to implement these requirements if sponsored by us.

The answer is it depends. I've only done one such work for supporting [springfox in grails framework](https://github.com/springfox/springfox-grails-integration). I did take it up because I think it was in line with the direction of the library, and it [worked out pretty well](https://objectcomputing.com/products/grails/show-us-your-grails/). However, I grossly underestimated the effort :) Im certainly open to it. I'll DM you on gitter.
