### ISSUE TITLE
@ApiModelProperty.allowEmptyValue = true/false does not emit "allowEmptyValue" in swagger.json

### ISSUE THREAD

**Issue by bill-titus** [springfox/springfox#2021]
Using 2.7
	compile 'io.springfox:springfox-swagger2:2.7.0'
	compile 'io.springfox:springfox-swagger-ui:2.7.0'

What kind of issue is this?
 - [ x] Bug report.

public class MyClass {
    @ApiModelProperty(required = true, allowEmptyValue = true, value = "Some description")
    private String name;
}

EXPECTED:
Generated swagger.json would include "allowEmptyValue" attribute.

OBSERVED:
With value of either true or false, nothing is emitted in the generated doc.

**Comment by igorko** [comment]
I guess this caused regression. Just writing here, because you are aware of changes.
When I put auto-generated swagger into online swagger editor I get next error

> Schema error at definitions['MyClass'].properties['id']
> should NOT have additional properties
> additionalProperty: allowEmptyValue
> Jump to line 1523

and

> Schema error at definitions['MyClass'].properties['description']
> should NOT have additional properties
> additionalProperty: allowEmptyValue
> Jump to line 1523

And class definition is next
```
public final class MyClass {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @ApiModelProperty(readOnly = true)
    @Setter
    @Getter
    private String id;

    @NotNull
    @ApiModelProperty(required = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @Setter
    @Getter
    private String description;
}
```

Definition in swagger is next

>    MyClass:
>     type: object
>     required:
>       - description
>     properties:
>       description:
>         type: string
>         allowEmptyValue: false
>       id:
>         type: string
>         readOnly: true
>         allowEmptyValue: false
>     title: Source

As I understand allowEmptyValue is not valid property for scheme property. Btw I am using MyClass as @RequestBody.
Is it possible to avoid adding allowEmptyValue to property definition? In my case I have @NotNull and required = true, but none of them says value cannot be empty. I am using swagger-ui 2.8.0
