### ISSUE TITLE
Model attribute expansion should respect form/query parameter type

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#2376]
Reported https://github.com/springfox/springfox/issues/680#issuecomment-336436807 by @smthpickboy

The expanded parameters are always coming through with parameter type of query. It should inspect the consumes media type and determine the type.

**Comment by cedneve** [comment]
Hello @dilipkrish. I am using version 3.0.0 and I think this bug is still in that version. When an endpoint takes a multipart/form-data as input, the resulting swagger configuration contains two errors that have already been reported by numerous other users of springfox:
- the parameters/in is set to body instead of formdata
- the type and format are set in a parameters/schema instead of directly in parameters
Maybe the fix mentioned here did not find its way into 3.0.0 ?

**Comment by dilipkrish** [comment]
It was reworked and there are open tickets with multipart requests, they should be fixed in the next patch @cedneve

**Comment by cedneve** [comment]
Hi Dilip,

Thanks for your reply. If you need help to get it done, please let me know.
I made the changes by hand in the springfox generated swagger config file
on our project this time. I hope to get it right directly from v3.0.1 ;-)
Do you have a release date in mind ?

Thanks,
Cedric
