### ISSUE TITLE
Swagger for api versioning based on custom headers only

### ISSUE THREAD

**Issue by ankool** [springfox/springfox#2537]
Please take the time to search the repository, if your question has already been asked or answered.

I have a question while working on version - v2.9.2

I've implemented a @Version annotation for api versioning. This checks for date in "version" header of request and based on date comparison selects v1, v2, or v3 by implementing a custom RequestMappingHandlerMapping in the background

The final request mappings after version processing looks like 

```
V1:
"Mapped"{[/api/work/{vehicleId}],methods=[GET],produces=[application/json],custom=[com.work.version.service.VersionRequestCondition@390e814c]}"
 onto public org.springframework.http.ResponseEntity<com.work.models.WorkResponse>

V2:
"Mapped"{[/api/work/{vehicleId}],methods=[GET],produces=[application/json],custom=[com.work.version.service.VersionRequestCondition@1ed0128b]}"
 onto public org.springframework.http.ResponseEntity<com.work.models.WorkV2Response>
```

I am facing issue while creating dockets for both v1 and v2 as routes, methods, and produces are same but custom & responseEntity are different. As per the documentation we can use ApiSelectorBuilder to navigate based on produces but how do I select route based on custom or responseEntity.

Controller.class

```
V2

 @ApiOperation(value = "Work V2", notes = "", response = WorkV2Response.class)
 @Version(version = "2018-06-01")
 @RequestMapping(produces = { "application/json" }, method = RequestMethod.GET)
public ResponseEntity<WorkV2Response> getWorkV2(){}


V1

@ApiOperation(value = "Work V1", notes = "", response = WorkResponse.class)
 @Version(version = "2018-01-01")
 @RequestMapping(produces = { "application/json" }, method = RequestMethod.GET)
public ResponseEntity<WorkResponse> getWork(){}
```

SwaggerConfig.class

In this class I wish to create docket for both V1 and V2, but not clear how to map custom in Mapping above to decide version in swagger. The below code is incorrect as instead of header I need to match as per custom or responseEntity (based on mappings above)

```
@Bean
    public Docket swaggerV2() {
        return new Docket(DocumentationType.SWAGGER_2).groupName("v2").select().apis(p -> {
            if (p.headers() != null) {
                for (NameValueExpression<?> mt : p.headers()) {
                    if (mt.getName().equals("version")) {
                        if (mt.getValue() != "2018-06-01") {
                            return true;
                        }
                    }
                }
            }
            return false;
        }).build().genericModelSubstitutes(Optional.class).ignoredParameterTypes(ApiIgnore.class).apiInfo(apiInfoV2());
    }
```

**Comment by dilipkrish** [comment]
You can do something like

```java
@Bean
    public Docket swaggerV2() {
        return new Docket(DocumentationType.SWAGGER_2).groupName("v2").select().apis(p -> {
            if (p.findControllerAnnotation(Version.class).isPresent()) {
                    //and if version is v2...
            }
            return false;
        }).build().genericModelSubstitutes(Optional.class).ignoredParameterTypes(ApiIgnore.class).apiInfo(apiInfoV2());
    }
```

**Comment by volkovs** [comment]
@ankool did the suggested solution work?

@dilipkrish I have implemented similar approach for API versioning with custom `org.springframework.web.servlet.mvc.condition.RequestCondition`. As a result controller may have two almost identical (request handling) methods (only method name and custom Version annotation value are different).

I used `RequestHandler` selectors (like you mentioned here as well). But the problem is that from springfox point of view those two methods (`RequestHandler`s) are identical. So ONLY ONE RequestHandler comes in the loop `.select().apis(p -> {
            if (p.findControllerAnnotation(Version.class).isPresent()) {
                    //and if version is v2...
            }
            return false;
        }).`. As a result there is no possibility to select one of the handlers into specific version group.

In my understanding `springfox.documentation.RequestHandlerKey` is responsible for such behaviour.

So, I have a question. Do you think described scenario is valid and should be supported? And, if so, would enhancing of `RequestHandlerKey` would be the proper way of solving it?

**Comment by mccaffs** [comment]
I also have an issue trying to use header versioning to differentiate which request to route to.
I have a naive v1 & v2 of the same request as below

```
@PostMapping(value = "my_request", consumes = MediaType.APPLICATION_JSON_VALUE, headers = "API-VERSION=v1")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Successful v1"),
            @ApiResponse(code = 400, message = "Bad Request v1"),
            @ApiResponse(code = 500, message = "Internal Error v1")
    })
    public ResponseEntity<Object> requestV1() {
        return new ResponseEntity<>(HttpStatus.OK);
    }

    @PostMapping(value = "my_request", consumes = MediaType.APPLICATION_JSON_VALUE, headers = "API-VERSION=v2")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Successful v2"),
            @ApiResponse(code = 400, message = "Bad Request v2"),
            @ApiResponse(code = 500, message = "Internal Error v2")
    })
    public ResponseEntity<Object> requestV2() {
        return new ResponseEntity<>(HttpStatus.OK);
    }
```

then in my swagger config I have code to target each version independently so I can have a v1 & v2 grouping:

```
@Bean
    Docket swaggerDocV1() { return configureVersion("v1"); }

    @Bean
    Docket swaggerDocV2() { return configureVersion("v2"); }

    private Docket configureVersion(String version) {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName(version + " Api")
                .select()
                .apis(p -> {
                    if (p.headers() != null) {
                        for (NameValueExpression nve : p.headers()) {
                            if ((nve.getName().equals("API-VERSION")) && (nve.getValue().equals(version))) {
                                return true;
                            }
                        }
                    }
                    return false;
                })
                .build()
                .apiInfo(new ApiInfoBuilder()
                        .title("API documentation " + version)
                        .version(version)
                        .build())
                .useDefaultResponseMessages(false);
    }
```

In my swagger generated documentation I have the two groups, but both the v1 and v2 groups show the documentation for the v1 request (see the method name picked up, the descriptions for responses etc all show v1 instead of v2):

![Screen Shot 2019-03-25 at 10 22 52 AM](https://user-images.githubusercontent.com/28133403/54912285-3cbe6280-4ee8-11e9-8346-c82816628d78.png)


Is there any way to make this work using header based versioning? 
If not is this something intended to be supported in new releases?

**Comment by mccaffs** [comment]
I've found I can disable the logic which groups my matching requests together simply by disabling the RequestHandlerCombiner combination logic being used:

```
@Bean
    public RequestHandlerCombiner disableRequestHandlerCombiner() {
        return source -> source;
    }
```

**Comment by IncPlusPlus** [comment]
Thanks @mccaffs. I stumbled upon this when I was running into this exact issue. I am also implementing API versioning and each request handler method is annotated with a versioning related annotation. If there were two endpoint methods that were the same except for this annotation, they would get combined and I would only be able to list one of the methods. Using your solution, this no longer is a problem!

**Comment by dlangerenken** [comment]
Lifesaver @mccaffs !!
