### ISSUE TITLE
Cannot distinguish between operations annotated with @RequestMapping.params

### ISSUE THREAD

**Issue by gionn** [springfox/springfox#2541]
springfox 2.9.2, I've two methods in the same controller that use the params attribute in `@RequestMapping`.

It looks like that both are never rendered inside the spec, just one of them randomly.

``` 
@ApiOperation( value = "Retrieve products with a filter" )
@RequestMapping( method = RequestMethod.GET, params = "filter" )
public List<ProductDTO> getAllFilter(@RequestParam String filter){...}

@ApiOperation( value = "Retrieve products" )
@RequestMapping( method = RequestMethod.GET )
public List<ProductDTO> getAll(){...}
```

**Comment by gionn** [comment]
same happens also for `@RequestMapping( method = RequestMethod.GET, produces = CSV_CONTENT_TYPE )`.

Does springfox takes in account only request method and path to distinguish different operations?

**Comment by dilipkrish** [comment]
The randomness of this bug has been fixed in 3.x. However regarding the the rest
- The adding the `filter` params is probably getting lost because swagger specification does not support having more than two paths with different query params. You can get around it by using the experimental feature to `enableUrlTemplating` in your docket.
- the second problem you mention, should be fixed as well giving you one operation that has two producing media types.

**Comment by gionn** [comment]
Thanks, I will look forward to test v3 soon.
