### ISSUE TITLE
Adding tags and description with ApiListingScannerPlugin

### ISSUE THREAD

**Issue by mushketyk** [springfox/springfox#2545]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? 

2.7.0

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 

I need to add a custom API description with `ApiListingScannerPlugin`. It works, but it sets "default" for the API description and adds no tags. Here is how the example from the Springfox documentation is rendered in my case:

![image](https://user-images.githubusercontent.com/592286/42447701-b0f16bd0-8372-11e8-912a-3a7f78712dd1.png)

Is there a way to add description and tags for this API?  Do I need to implement another plugin to override these defaults?

**Comment by dilipkrish** [comment]
You can add an `@Api(tags={"Your Description"}` to your controller

**Comment by fstrudel** [comment]
@dilipkrish I have a similar issue with the latest 2.9.2 version. I am using `ApiListingScannerPlugin` because I don't control the source code of the controller (so I can't add `@Api...` to it), but still want to have them documented, like the Spring Boot health endpoint for example.
I believe that since there were no tags, all my custom API descriptions were ending up at the end of the UI list of tags instead of being in the alphabetical order as it was in version `2.7.0`.
I had to define the tags globally to have them appear in the correct order:
```
 @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2).build().tags(new Tag("health-endpoint", "Health endpoint");
}
```
and then associate in my custom operation, the tag "health-endpoint".
It then worked fine.

Is this the correct/expected way to do it?
