### ISSUE TITLE
Swaggerfox 2.5.0 supports the custom request-body and treated it as body type. But the latest version 2.9.2 is not supporting.

### ISSUE THREAD

**Issue by NarendhiranBala** [springfox/springfox#2548]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by dilipkrish** [comment]
@NarendhiranBala if you need it to behave like a request body then you need to annotate it as `@RequestBody`

**Comment by gmanraj** [comment]
@dilipkrish In spring hibernate, we found that the best way for updating entity partially by introducing a custom request parameter for RequestBody. We tried this suggestion ( https://stackoverflow.com/questions/18226629/hibernate-update-object-partially ) too, but not helpful with Swagger.

APIs are working as expected with body data when we hit this APIs using "Postman" tool, we faced issues only swagger API docs generator. I tried with ModelAttributes for header and body but they are rendered as query parameters instead of header and body (version 2.8.0 and 2.9.1).

Currently, we have managed with  `ignoredParameterTypes(PatchRequestBody.class) ` and `@ApiImplicitParams(..., paramType = "body")` for swagger API.
