### ISSUE TITLE
Swagger does not respect Jackson @JsonIgnoreProperties annotation

### ISSUE THREAD

**Issue by guan25** [springfox/springfox#2613]
When I used @JsonIgnoreProperties annotation to ignore some redundant properties from the super classes, it has completely no effect on Swagger. The consequence is the API document and the real Json objects have inconsistent structure. Does anyone know how we can solve this problem?

@JsonIgnoreProperties(value = {"houseNo","coNo","coName","reviewer","latelyMonthLookTimes"
,"reviewTime"})
public class SecondHouseBrokerInVo extends SecondHouseVo {

}

**Comment by dilipkrish** [comment]
This is a known issue

**Comment by RodolpheGohard** [comment]
Hello, it seems the issue is still there (see also https://github.com/springfox/springfox/issues/113)

Any plan of fixing it ? or any workarounds ?

**Comment by jmformenti** [comment]
In some cases a workaround for this issue is overload the getter of parent property and use @JsonIgnore, i.e:

```java
@JsonIgnore
public Links getLinks() {
  return super.getLinks();
}
```

**Comment by Artheriom** [comment]
Hi, 

I currently have this problem on my project. This is insane, because some of my objects are linked to another objects, etc. My scheme is completely wrong due to this problem. Is there any workaround for this ? Or, at least, a way to tell Springfox to not go further than one or two indirection level ?

**Comment by svpr3m0** [comment]
@dilipkrish Could this issue be addressed at some moment in the 3.x line? I've run into this problem a lot of times in the last 5 years so it'd be great if it could be fixed.

**Comment by Artheriom** [comment]
Hi @svpr3m0. I agree that it would be great to fix this issue. Howewer, i've found a workaround, using JsonView (which is supported in 3.0.0 SNAPSHOT - see https://github.com/springfox/springfox/issues/3333) instead of JsonIgnoreProperties. 

This modification implies some changes on the code, but are mainly limited to annotations. :)

**Comment by svpr3m0** [comment]
@Artheriom Thanks for the suggestion, but it won't help in my case. I need to ignore the `suppressed` property that is inherited in my `DepartmentNotFoundException`when extending `Exception`/`RuntimeException`:

```
    @ApiOperation(value = "Create department")
    @ApiResponses({
            ...
            @ApiResponse(code = 404, message = "Error de validación", response = DepartmentNotFoundException.class),
            ...
    })
    @GetMapping(value = "/v1/department/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
```
Since getSuppressed is final I can't override that method to place a `@JsonIgnore` annotation on the setter. That's where `@JsonIgnoreProperties` would come in handy.
```
    public final synchronized Throwable[] getSuppressed() {
```

**Comment by Jojoooo1** [comment]
still no solution ?

**Comment by dilipkrish** [comment]
@Jojoooo1 will try and see if I can fix

**Comment by manucr619** [comment]
is this issue Fixed ? any updates on this ?

**Comment by Kiran-N** [comment]
Tried with 3.0.0 release but not working.

**Comment by jennyadobreva** [comment]
Use &lt;templateResourcePath&gt; option in the configuration.
I added a fix to my code, extracting the oneof_interface.mustache and adding the following lines:
{{#jackson}}
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

{{/jackson}}
after the first line and it works.
