### ISSUE TITLE
Feature: Adding a package to scan for models in the docket configuration

### ISSUE THREAD

**Issue by akuma8** [springfox/springfox#2659]
I don't know if it's already possible but it would be nice to add the ability to specify packages where our models are located. Typically in my app, I have configured 4 dockets, each docket has a groupname and its own api basepackage but not for models. On swagger-ui I would like to see only models related to the docket groupname in the "Model" section but currently it is not the case. 
It would work like the JPA EntityManager where classes annotated with `@Entity` are picked up. For Springfox the mark up would be `@ApiModel` and in our configuration having something like:
```
    @Bean
    public Docket docket1Config() {
        return new Docket( DocumentationType.SWAGGER_2 )
                .groupName( "first doc" )
                .select()
                .apis( basePackage( "io.springfox.v1.controller" ) )
                .paths( any() )
                .models(ModelSelectors.basePackage("io.springfox.v1.dto") // add this
                .build()
```
And 
```
    @Bean
    public Docket docket2Config() {
        return new Docket( DocumentationType.SWAGGER_2 )
                .groupName( "second doc" )
                .select()
                .apis( basePackage( "io.springfox.v2.controller" ) )
                .paths( any() )
                .models(ModelSelectors.basePackage("io.springfox.v2.dto") // add this
                .build()
```

**Comment by akuma8** [comment]
Yes. The goal is to associate some models to a specific Docket. And currently only models used in controllers are visible on the ui and with this feature all models will be visible, helping a lot front-end developers since they could anticipate the models.

**Comment by niebaraka** [comment]
I also would like to have such feature. The reason is that besides rest data model I also have e.g. kafka model which I want to be documented too. Maybe it is misusing of swagger documentation but I think swagger matches my needs. I'm planning to use rest documentation online and offline, and kafka only offline. I would introduce some fake controller in test configuration for this purpose and specify additional models with some package, because now I can only specify each class manually which is too annoying. Then offline documentation for kafka model could be generated with Swagger2Markup.

**Comment by dilipkrish** [comment]
It is pretty trivial to write your own machinery that scans your custom models and loads it using the `docket.additionalModels` the challenge will be to surface those models when using endpoints correctly
