### ISSUE TITLE
Will enableUrlTemplating ever stop "incubating"?

### ISSUE THREAD

**Issue by theemathas** [springfox/springfox#2670]
According to the source code, the [enableUrlTemplating](https://github.com/springfox/springfox/blob/d6c72bf8623b3efaebb3e276154cf98f5fdf8af6/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/Docket.java#L386) method in Docket is marked as "incubating" since version 2.1.0, which was released in July 2015 (3 years ago). Furthermore, this feature requires depending on [springfox-swagger-ui-rfc6570](http://mvnrepository.com/artifact/io.springfox.ui/springfox-swagger-ui-rfc6570), which was last released in 2016, two years ago. When will this feature stop being experimental?

**Comment by theemathas** [comment]
Actually, I tried using the usual springfox-swagger-ui dependency, and enableUrlTemplating seems to work. Is this a mistake in the [documentation](http://springfox.github.io/springfox/docs/2.7.0/#springfox-rfc6570-support-strong-incubating-strong)?

**Comment by dilipkrish** [comment]
@theemathas the reason this is experimental is because open api spec doesnt officially supported. Not because its currently being experimented on.

Also the swagger-ui has changed completely and become react based and the rfc6570 version hasn't been updated to reflect that. However, you can still use it, it will not have any updates and bug fixes from the mother project however.
