### ISSUE TITLE
Primitive RequestPart parameters generate incorrect Swagger Model

### ISSUE THREAD

**Issue by ghost** [springfox/springfox#2717]
Method parameters of the following form will generate incorrect parameters in Swagger 2. Non-validating parsers will not immediately choke on it, but code generators like swagger-codegen or openapi-codegen will.

```java
  public SomeReturnValue webMethod(
    @RequestPart("file") MultipartFile file,
    @RequestPart("description") String description) {
...
```

The generated spec will look like this:
```json
                    {
                        "name": "file",
                        "in": "formData",
                        "description": "file",
                        "required": true,
                        "type": "file"
                    },
                    {
                        "in": "formData",
                        "name": "description",
                        "description": "description",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
```

This is a problem because parameters with ``in=formData`` can't have a schema, only a type is allowed. The spec doesn't allow formData parameters to be anything other than a primitive.

The expected JSON should be:
```json
                    {
                        "name": "file",
                        "in": "formData",
                        "description": "file",
                        "required": true,
                        "type": "file"
                    },
                    {
                        "in": "formData",
                        "name": "description",
                        "description": "description",
                        "required": true,
                        "type": "string"
                    }
```

**Comment by shartte** [comment]
Alright, I see that a contract test is failing that relates to #1965 apparently.
Using https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject as the reference, I do not believe that set of test data is actually compliant with the spec.

The spec says that only name, in, description, and required are "fixed" fields.
`schema` is only valid for parameters with `in=body`, which cannot coexist with `in=formData`.

It also specifically says the following:
`The type of the parameter. Since the parameter is not located at the request body, it is limited to simple types (that is, not an object).`

It only seems valid to model a JSON document sent via a formData multipart as `type=string` in Swagger 2.

**Comment by jowko** [comment]
I also encountered this problem. It worked correctly on 2.7.0 version and broke on 2.8.0 version (problem was discovered when I wanted to upgrade this library).
Probably this problem is related: https://github.com/springfox/springfox/issues/2855
Invalid model was generated for every endpoint with has RequestPart annotation.

Currently I'm forced to stay on old version.

**Comment by hovorkap** [comment]
Hi, I am having the same problem

```
  @PostMapping(path = ["/verify/probe-image"], produces = [MediaType.APPLICATION_JSON_VALUE], consumes = [MediaType.MULTIPART_FORM_DATA_VALUE])
    fun usingProbeImage(@RequestPart(name = "probe") @ApiParam(value = "File", required = true) probe: MultipartFile,
                        @RequestParam(name = "reference") reference: String)
```

generates this:

```
/api/v1/configuration/tools/face-verifier/verify/probe-image:
    post:
      tags:
        - face-verifier-controller
      summary: usingProbeImage
      operationId: usingProbeImageUsingPOST
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: probe
          in: formData
          description: File
          required: true
          type: file
        - in: formData
          name: reference
          description: reference
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Score'
      deprecated: false
```
Is there any workaround to avoid having
          schema:
            type: string
instead of just type: string ?

**Comment by msangals** [comment]
I'm running springfox at version 2.9.2

When you build a custom ApiDescription with the ParametersBuilder as follow:

```
new ParameterBuilder()
    .name("password")
    .parameterType("formData")
    .required(true)
    .modelRef(new ModelRef("string"))
    .build()
```

Generates the same broken JSON for formData:

```
                   {
                        "in": "formData",
                        "name": "password",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
```

The expected valid JSON is:

```
                   {
                        "in": "formData",
                        "name": "password",
                        "required": true,
                        "type": "string"
                    }
```

**Comment by spylightadmin** [comment]
We have the same problem in v2.9.2, any update on this?

**Comment by kremers** [comment]
Same Problem with 2.9.2!

**Comment by joistick11** [comment]
Same
