### ISSUE TITLE
Description Table markdown not rendered

### ISSUE THREAD

**Issue by AmayaRuiz** [springfox/springfox#2867]
Hi!

I am using:
    springBootVersion = '**2.0.2.RELEASE**'
, and:
    compile 'io.springfox:springfox-swagger2:**2.7.0**'
    compile 'io.springfox:springfox-swagger-ui:**2.7.0**'

And the table markdown in .yaml descriptions, is not rendered.

My .yaml, is like this:
```
paths:
  /config/validation:
    get:
      description: |
        Retrieve all configuration properties used for validation.

        | **Profile** | **Description** |
        | ------- | -------- |
        | Chinese   | true   |
        | International   | true    |
      tags:
        - config
      operationId: getValidationConfig
```
, and I am getting this on the screen:

![renderproblem](https://user-images.githubusercontent.com/46685597/51176229-4b6b1680-18b4-11e9-9a5c-1258fbd0ab7b.png)

Upgrading the version to the **2.9.2.**:
    compile 'io.springfox:springfox-swagger2:**2.9.2**'
    compile 'io.springfox:springfox-swagger-ui:**2.9.2**'
, I have the same behavior .

But trying from https://petstore.swagger.io/ , it works:

![renderproblemswaggereditor](https://user-images.githubusercontent.com/46685597/51176036-d0a1fb80-18b3-11e9-9730-fa351ca13eb3.png)

And I need that specific kind of markdown, because I also need to render the table in .pdf, with asciidoctor (I mean, I need to show the markdown in both places, on the API screen, and in the .pdf documentation).

Any ideas, will be wellcome :)

**Comment by tlsJP** [comment]
While not the most helpful, the high level issue seems that the generated interface annotated with @ApiOperation has a 'notes' field that does not include '\n' to separate lines within the value.

Manually modifying that field to include '\n' will then display the MD correctly, but this obviously is not desirable since this is supposed to be generated code.

I tried adding '\n' into the yaml file to try and force it that way but when the interface is generated, the newline character is replaced with a blank space... so that didn't work either.
