### ISSUE TITLE
Api Model property not working for Java Library Classes

### ISSUE THREAD

**Issue by reddyonlinenow** [springfox/springfox#2982]
ApiModelProperty hidden doesnot work for java objects

public class MyClass {

@ApiModelProperty (hidden = true)
private MySubSclass subclass;

public MySubSclass getMySubSclass(){
return subsclass;
}
public void SetMySubSclass(MySubSclass sc) {
MySubSclass = sc;
}
}

public class MySubSclass {
private String str;
}

MySubclass is still shown as part of Api Doc in Request Object

used
swagger2
springfox 2.9.2
spring boot
java 8
maven 3+

please help

MyClass has reference to URL, it is showing all the variables of URL in swagger request API

My request Param is the variables of MyClass

**Comment by dilipkrish** [comment]
Try placing it on the getter

**Comment by reddyonlinenow** [comment]
it did not work either

**Comment by reddyonlinenow** [comment]
@dilipkrish did you get a chance to look into this?
please let me know the fix around, thanks a lot for your help

**Comment by jonflacke** [comment]
We have a custom Java class repeated in many , many places in our entities which gets converted from a specifically formatted string value into the corresponding object value. The end users should never know what the actual object looks like and therefore we _must_ obscure the value and provide an example. We cannot use Swagger2 until this issue is fixed.

**Comment by InnuceEAN** [comment]
I like unfixed closed issues

**Comment by dilipkrish** [comment]
@InnuceEAN linked to an open related issue. Thank you for commenting, stale bot doesn't like inactivity :) So I rely on members of the community to indicate if an issue needs to be re-opened which is better than one person triaging 800+ issues.
