### ISSUE TITLE
Swagger oAuth error

### ISSUE THREAD

**Issue by Ripul89** [springfox/springfox#3005]
Hi All,
I am new to swagger, i am using spring boot i have configured all the things and i am using client Credentials after hitting the oauth server in am getting below as response

{"error":"invalid_client","error_description":"Browser requests to the token endpoint must use Proof Key for Code Exchange."}

but i am expecting token.Please help me on this

**Comment by Ripul89** [comment]
@phenbach
@chanurahemal
@dilipkrish

**Comment by phenbach** [comment]
What service are you using?

**Comment by Ripul89** [comment]
Thanks a lot for your response. I am using Spring Boot and i am having a rest controller.For oAuth i am using OKTA.Swagger UI is working fine but Authorize is not working

**Comment by Ripul89** [comment]
Even i have added the same question in stackoverflow [https://stackoverflow.com/questions/56358067/springboot-swagger-oauth](url)

**Comment by phenbach** [comment]
I am not familiar with that Framework. The issue I had with Swagger was a bug within distribution that needed to be resolved. You issue appears to be about the feature PKCE. You may want to look deeper into either disabling the security feature or how to properly get Swagger UI to transmit it. Here is a thread I looked up about it https://github.com/swagger-api/swagger-ui/issues/3953 maybe that can get you started.

**Comment by Ripul89** [comment]
Thanks a lot for your reply

**Comment by Ripul89** [comment]
Hi @phenbach,
How to remove origin header form the request?

**Comment by chenkang2208** [comment]
I'm getting the same issue. I guess we are expecting the feature adding support to PKCE just like what swagger ui had already implemented.(refer to https://github.com/swagger-api/swagger-ui/pull/5361).
Would you help add a flag like `SecurityConfiguration.usePkceWithAuthorizationCodeGrant(true)` to enable this kind of feature?

**Comment by phenbach** [comment]
@chenkang2208 unfortunately I am not on the swagger dev team, so I am unable to help with that.

**Comment by chenkang2208** [comment]
@phenbach Thanks for responding. I looked into `springfox-swagger-ui `source code today. And found it has dependency on swagger-ui version 3.17.1 which doesn't contain PKCE support feature. swagger-ui PKCE support feature was released since version 3.24.0 on Oct 12, 2019. Since swagger-ui V3.24.0, the `initOAuth` method provided one more flag `usePkceWithAuthorizationCodeGrant` to enable PKCE for Authorization Code Flow.

So I'm wondering whether you can **upgrade the swagger-ui version** and add the PKCE support feature?
Thanks a lot.

![image](https://user-images.githubusercontent.com/7448127/73720755-a8569a80-475d-11ea-9572-e58560755add.png)

![image](https://user-images.githubusercontent.com/7448127/73720546-34b48d80-475d-11ea-936a-2d62da495197.png)

![image](https://user-images.githubusercontent.com/7448127/73721413-27000780-475f-11ea-8007-1c946d451e8c.png)

**Comment by emmaLP** [comment]
This issue affects springfox version 3 as well.
