### ISSUE TITLE
Model property order is no longer respected as of 2.9.2

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#3087]
This seems to be broken again as of 2.9.2

_Originally posted by @franz-see in https://github.com/springfox/springfox/issues/1280#issuecomment-516498746_

**Comment by Tristan107** [comment]
I've just noticed this issue in SpringFox 2.9.2, so I switched back to 2.8.0, but in this version I noticed that (using latest Oracle JDK 8) :

* swagger json is generated using the order of fields (not properties, and not ApiModelProperty "positions")

For example :

```
@ApiModel
public class TokenRequestDto {

  @ApiModelProperty(required = true, position = 2)
  private String user;
  
  @ApiModelProperty(required = true, position = 1)
  private String password;
}
```
will give the same as :
```
@ApiModel
public class TokenRequestDto {

  @ApiModelProperty(required = true, position = 1)
  private String user;
  
  @ApiModelProperty(required = true, position = 2)
  private String password;
}
```
will give the same as :

```
@ApiModel
public class TokenRequestDto {

  @ApiModelProperty(required = true)
  private String user;
  
  @ApiModelProperty(required = true)
  private String password;
}
```
and will always give this :

```
"parameters": [
{
"name": "user",
"in": "query",
"required": true,
"type": "string"
},
{
"name": "password",
"in": "query",
"required": true,
"type": "string"
}
}
],
```

I don't know if it's a coincidence since I'm aware you have no guarantee on the field order using java reflection :

getFields()

Returns an array containing Field objects reflecting all the accessible public fields of the class or interface represented by this Class object. The elements in the array returned are not sorted and are not in any particular order. This method returns an array of length 0 if the class or interface has no accessible public fields, or if it represents an array class, a primitive type, or void.

source : https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getFields--

**Comment by Tristan107** [comment]
By the way, is there any ETA for this blocking issue ?

**Comment by HiAscend** [comment]
i have the same question too，version springfox-swagger2  2.9.2，what can i do?

**Comment by cemo** [comment]
@dilipkrish this is crucial too.

**Comment by jcballesteros** [comment]
This issue already exists, any temporal solution?

**Comment by miamilabs** [comment]
This issue still exist in 2.10.5

**Comment by dilipkrish** [comment]
Oh my gosh.. let me see what I can do

**Comment by dilipkrish** [comment]
Hope this works better for u

**Comment by schrek1** [comment]
looks still broken, model properties are alphabetically sorted
