### ISSUE TITLE
Version 2.10 breaks with Unable to Infer base url

### ISSUE THREAD

**Issue by samudurand** [springfox/springfox#3335]
Version used: 2.10.0

 We upgraded from 2.9.2 to the recently released 2.10.0. Our Spring setup was working until we switch to that new version. Now the `/swagger-ui.html` throws a message box saying `Unable to infer base url`. 

In the logs we can see a large amount of lines similar to this: 

`288180 [http-nio-9090-exec-3] INFO  u.g.h.d.l.c.RequestLoggingFilter - GET /null/swagger-resources/configuration/security took 0ms and returned 404 `

**Comment by dilipkrish** [comment]
Oh please dont use 2.10... it was an intermediate step so that people who were on 3.0.0-SNAPSHOT can continue using a released version if needed. Please continue 3.0.0-SNAPSHOT. Thats the version with the OAS support. Its not ready yet, should be available tomorrow 🤞

**Comment by dilipkrish** [comment]
Would love your feedback once the build is fixed!

**Comment by dilipkrish** [comment]
The [latest snapshot ](https://github.com/springfox/springfox/issues/3070#issuecomment-648578094)has landed with open API 3.0.3 support!

**Comment by samudurand** [comment]
Thanks for the quick answer, so what version should we be using then ? The highest I see is 2.10.5 ?

**Comment by TristanCP** [comment]
Just to let you know, the same exact anomaly is present in 2.10.5 (local test with no reverse-proxy, no spring security, no context path) : 
When I try to reach : http://localhost:8080/swagger-ui.html

I get this in console (the no context path is interpreted as "/null/" context path) : 
![image](https://user-images.githubusercontent.com/6929937/99405018-8db87100-28ec-11eb-8ece-116cff12b529.png)

If the "dont use 2.10..." advice applies to all "2.10.x" versions, maybe you should remove them from Maven, because this 2.10.5 version looks like it's the last before the next big major version with many breaking changes (3.0.0).

**Comment by ioannisNoukakis** [comment]
> Oh please don't use 2.10
Well, we are stuck cause we don't have time to upgrade to 3.0.0 and still want to get rid of the CVE plaguing 2.9.x. XD
