### ISSUE TITLE
Support for JSR-303 (Java Bean Validation) ?

### ISSUE THREAD

**Issue by omayevskiy** [springfox/springfox#356]
Hi is there any support for JSR-303 (Java Bean Validation) ?

Given

A controller method
```
import javax.validation.Valid;
@RequestMapping(method = RequestMethod.PUT)
    public void create( @RequestBody @Valid MyDTO myDTO) {
        // do something with myDTO
    }
```

A command object
```
import javax.validation.constraints.NotNull;
public class MyDTO {

    @NotNull
    private Long myId;

    @NotNull
    private String myValue;
```

Swagger produces
```
MyDTO {
   myId (integer, optional),
   myValue (string, optional)
}
```

But should be

```
MyDTO {
   myId (long?, required),
   myValue (string, required)
}
```

I could add swagger annotations to MyDTO's fields, but then the NotNull/required logic would be duplicated and potentially leads to documentation inconsistence.

Thx for reading ;-)

**Comment by jasonchaffee** [comment]
It would be nice if it could handle this not only in the model, but for Query, Path, Matrix params as well.  Also, it would nice if it would handle more than @NotNull and could handle the other annotations as part of the spec.  See http://docs.oracle.com/javaee/7/api/javax/validation/constraints/package-summary.html

Then, the clients of the swagger spec, such as the swagger-ui could validate the fields as they are entered without needing to make a call to the server.

**Comment by adrianbk** [comment]
Relates to this issue: https://github.com/springfox/springfox/issues/311

As far as I can tell none of the JSR-303 constraint's are supported by springfox (including @NotNull).
It should be relatively straight forward to offer rudimentary support for these constraints but we would have to provide a way to disable the feature because there are scenarios, such as using [groups](https://docs.jboss.org/hibernate/validator/4.0.1/reference/en/html_single/#validator-usingvalidator-validationgroups) to conditionally apply validation rules based on runtime conditions, where it is not feasible to try to infer validation constraints.

@jasonchaffee would you be interesting in contributing to your idea?

**Comment by dilipkrish** [comment]
I prefer this to be separate module ```springfox-validations```. Should be simple enough to use the plugin models to enrich the service descriptions. 

Don't want it to be a concern in the core modules, just because it can be released incrementally and possibly out-of-band.

**Comment by jasonchaffee** [comment]
I agree that it makes sense to be in a separate module.

**Comment by jasonchaffee** [comment]
If I can get some extra time I can take a stab at it.   It isn’t a high priority for our use right now, so that might limit the time I will have to look into it.  If that were to change, I would definitely take it on.

**Comment by NarendraPeddineni** [comment]
Hi is there any support for JSR-303 (Java Bean Validation) ?

**Comment by NarendraPeddineni** [comment]
is the  support for JSR-303 (Java Bean Validation) available  ?

**Comment by jfiala** [comment]
I added a sample implementation of NotNull and Min/Max to issue #987.

**Comment by jfiala** [comment]
Please let me know if I also should add support for the @Email (resolving to type "string").

**Comment by jfiala** [comment]
Pls also let me know what is the best way to add test cases for this in the petstore?
(where should I put them?)
