### ISSUE TITLE
io.swagger.v3.oas.annotations.headers.Header annotations seems to be ignored

### ISSUE THREAD

**Issue by michalaron** [springfox/springfox#3804]
Trying to define custom response header with oas annotation io.swagger.v3.oas.annotations.headers.Header  like:

```java
@Operation(summary = "Operation description")
  @ApiResponse(responseCode = "200", description = "Success", headers = {@Header(name = "custom-header", description = "Custom header description", schema = @Schema(implementation = String.class))})
  @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
  public SomeObject myMethod(...)
```

But no header information is generated to swagger JSON (in responses section for the given operation).

**Comment by fisco-unimatic** [comment]
I think the problem is in the OpenApiResponseReader. It's [isSuccessful method](https://github.com/springfox/springfox/blob/ab5868471cdbaf54dac01af12933fe0437cf2b01/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/OpenApiResponseReader.java#L159) always returns false when I debug it, so the headers aren't added. I think the String code needs to be parsed to an int.

    HttpStatus.Series.SUCCESSFUL.equals(HttpStatus.Series.valueOf(Integer.parseInt(code)));

**Comment by fisco-unimatic** [comment]
@michalaron As a workaround, you can copy and paste the OpenApiResponseReader class into your source, so that it will be registered as a Spring bean (you'll have to change its name, e.g. to MyOpenApiResponseReader), and parse the status code to an integer as described above.

You'll also need to add an empty content to your `@ApiResponse` annotation (which I think is another defect - you shouldn't need to do this):

    @ApiResponse(
            responseCode = "200", 
            description = "Success",
            content = @Content,
            headers = @Header(name = "custom-header", description = "Custom header description"))

Alternatively, as you've made your own copy of [the reader](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/OpenApiResponseReader.java#L140), you can move this line down outside the for-loop.

    headers.putAll(headers(apiResponse.headers()));
