### ISSUE TITLE
Request: Add Support for Spring Native

### ISSUE THREAD

**Issue by goafabric** [springfox/springfox#3816]
Hello,
it would be lovely to have support for spring native, graalvm binaries.
I created an issue in the spring-native project
https://github.com/spring-projects-experimental/spring-native/issues/777

But sdleuze asked me to open an issue here instead, so he can support the process.
As Swagger is already working with micronaut and quarkus, it should be possible in theory.
Thx.

**Comment by sdeleuze** [comment]
If somebody is interested to contribute this, I can provide some guidance.

**Comment by potjerodekool** [comment]
@sdeleuze 

I would be interrested but have issues to run the tests and such.

When I open a spock test in Intellij it shows the green run buttons but when I try to run a test it reports that no test can be found.

Also running with gradle gives problems. Looks like old spock and groovy versions are used.

s/modules-2/files-2.1/org.spockframework/spock-core/1.3-groovy-2.5/6f0df2cf4549dcc4b914971675da7e224e893e82/spock-core-1.3-groovy-2.5.jar!/META-
INF/services/org.codehaus.groovy.transform.ASTTransformation  because of exception org.spockframework.util.IncompatibleGroovyVersionException: The Spock compiler plugin cannot execute because Spock 1.3.0-groovy-2.5 is not compatible with Groovy 3.0.7. For more information, see http:
//versioninfo.spockframework.org

Would be nice I would know what I need to get started with the code.

**Comment by sdeleuze** [comment]
The GraalVM team has just released https://github.com/graalvm/native-build-tools in collaboration with us, this should allow you to run Junit 5 tests in native.

**Comment by potjerodekool** [comment]
I think the files can be generated during build. Only the host is not known during build time but that one can be replaced when the application runs. I created a little poc which uses the asm library:

https://github.com/potjerodekool/native-fox/blob/master/native-fox/src/test/kotlin/org/platonos/fox/SwaggerGeneratorTest.kt

**Comment by JayantSSable** [comment]
> If somebody is interested to contribute this, I can provide some guidance.

Hello Sébastien,

Could you please provide an approximate time (hours) which will be needed to finish this task? 
If I get an idea about the time needed, I can plan and contribute if possible.

PS: I'm completely new to spring-fox and spring-native, but experienced in java & spring-boot. 

Thanks.

**Comment by sdeleuze** [comment]
Sorry I can't, no idea.

**Comment by JayantSSable** [comment]
> Sorry I can't, no idea.

Okay. But any idea where the changes would be needed? Springfox or on Spring native or on both sides. That way we can ask someone from springfox for approx. estimate.

**Comment by potjerodekool** [comment]
I just started working on a maven plugin to generate the documentation during build time with springfox.
Going to use placeholder for things that are not known at buildtime. During runtime those placeholders can be replaced
with the correct values.

For now I have the code in my own repository but I want to contribute the code to the springfox project later.
https://github.com/potjerodekool/springfox-native

**Comment by sdeleuze** [comment]
> Okay. But any idea where the changes would be needed? Springfox or on Spring native or on both sides. That way we can ask someone from springfox for approx. estimate.

The native configuration should be provided on Spring Fox side via JSON native configuration. If dynamic features need to be provided you can use a GraalVM feature (not ideal since not really a supported API) or build time transformations (that's maybe what @potjerodekool tries to achieve).
