### ISSUE TITLE
Improper Input Validation: https://snyk.io/vuln/SNYK-JAVA-IOSPRINGFOX-1317096

### ISSUE THREAD

**Issue by neerazz** [springfox/springfox#3894]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)
- Yes

What kind of issue is this?

 - [x] Question. Is this a question about how to do a certain thing? 
 - No
 - [x] This is to fix the vulnernability : https://snyk.io/vuln/SNYK-JAVA-IOSPRINGFOX-1317096

 - [x] Vulnernability report:
    - [x] springfox specific configuration if it makes sense

**Comment by SMarchiano** [comment]
Hi @dilipkrish, @adrianbk, @martypitt - The SNYK link that @neerazz provided above indicates that "_A fix was pushed into the master branch but not yet published._"  Would you be able to publish a new version of **springfox-swagger2** that includes the fix for this issue?

@neerazz - Have you identified any other workaround/fix for this vulnerability or replacement for this library?

**Comment by neerazz** [comment]
@SMarchiano I have to move to springdoc-openapi-ui, which is almost same. 
Here is the link: https://springdoc.org/#getting-started
