### ISSUE TITLE
Adding Models using ApiImplicitParam

### ISSUE THREAD

**Issue by t0mgrant** [springfox/springfox#468]
I would like to add a Model to the models array in the generated swagger json.  I am defining a param on my controller via the @ApiImplicitParam annotation.  The resulting operation parameter json looks correct, it states the data type is "Options", but there is no "Options" model in my models array.  

@ApiImplicitParams(value={
    @ApiImplicityParam(name="options", paramType="form", dataType="Options", required=false)
})

The generated operation parameter looks good...
...
{
    name="options",
    description="options",
    defaultValue="",
    required=false,
    type="Options",
    paramType="form",
    allowMultiple=false,
    paramAccess=""
}

... but the models section is empty...

models : {
}

I've tried the annotation with the datatype using the fully qualified class name and also using just the simple name.  Neither value results in the model being added to the generated json.  I also tried adding an OverrideConverter to the ModelConverters to try to map "Options" to my model definition, but that didn't make a difference, but felt like the right direction.

How can I add my model to the swagger json?  Is there a way to add it explictly via another annotation or via code on the SwaggerSpringMVCPlugin or SwaggerGlobalSettings?  I don't really want to put the parameter in my controller's method signature, as i'm currently pulling it out from the HttpServletRequest, it is optional, and I don't want any failure in parsing to raise an exception.  ApiImplicitParam seemed like a perfect fit.

A side note: the ApiImplicitParam annotation is a little different than the others because it takes the dataType as a String value instead of a Class.  It would be nice if it was consistent, but that change would have to be upstream in swagger-core.

**Comment by jimhooker2002** [comment]
My use case looks like this:

    @ApiImplicitParams(@ApiImplicitParam(dataType = "Session", name = "session", paramType = "body"))
    public Session patch(@PathVariable long id, HttpServletRequest session) {

I need the HttpServletRequest so that I can call getInputStream() on it.  I need the raw JSON so that I can feed it through https://github.com/daveclayton/json-patch.  The JSON once deserialized into a model object is no good to me (once deserialized I can't tell which parts of the model are defaults and which parts got set as part of the original JSON).

So, I need a HTTPServletRequest as the input to my controller method, but I'd like to document the real data type in the Swagger UI.

Currently only base types are supported here: https://github.com/springfox/springfox/blob/ff512629f1adf4ef146f367efa29c0c3b3664b7c/springfox-swagger-common/src/main/java/springfox/documentation/swagger/readers/operation/OperationImplicitParameterReader.java#L83

If this method allowed the class name to be passed through i.e. support for more than just base types then the Swagger docs would be generated showing the correct model.

I can't see any work-around currently.  For now my HttpServletRequest params have only a name specified and the data-type is set merely to object (not very helpful).

**Comment by jimhooker2002** [comment]
Any chance this issue can be re-opened please?

**Comment by dilipkrish** [comment]
@jimhooker2002 Please create a new issue if you think this is a new/existing issue that still exists. Issues closed a long time ago, like this one, lose context to what you exact problem is and muddy older issues with unrelated problems.

Having said that, let me think about it a little and respond.

**Comment by jimhooker2002** [comment]
Thanks @dilipkrish.  I just submitted PR: https://github.com/springfox/springfox/pull/1529/ as an initial attempt at a fix (it works on my local machine with swagger-ui etc).  If it looks sensible then I'll 1) create the new ticket to track getting this pulled over and 2) add unit tests (the current PR was an initial attempt more for feedback than anything else - it seems to work however).
