### ISSUE TITLE
${pageContext.request.contextPath} not resolved

### ISSUE THREAD

**Issue by Vad1mo** [springfox/springfox#496]
when running http://localhost:8884/sdoc.jsp ${pageContext.request.contextPath} is not getting resolved.

How can I set ${pageContext.request.contextPath} or make it resolvable?

![bildschirmfoto 2014-11-18 um 14 02 05](https://cloud.githubusercontent.com/assets/1492007/5087808/d5e82b30-6f2c-11e4-9499-2d9539118302.png)

**Comment by ninaddk1980** [comment]
I am facing similar issue, while deploying my war file on tomcat. Do i have to set ${pageContext.request.contextPath} anywhere?

**Comment by barrygear** [comment]
For me, it was (in addition to jstl) tomcat-embed-jasper is not part of the spring-boot-starter-tomcat artifact and has to be added separately.

<dependency>
    <groupId>org.apache.tomcat.embed</groupId>
    <artifactId>tomcat-embed-jasper</artifactId>
</dependency>

**Comment by pacey** [comment]
I have found that adding a dependency on  compile 'org.apache.tomcat.embed:tomcat-embed-jasper:8.0.15' works when you run the application using bootRun or run the Application.java class in the IDE. But if you build a fat jar of the project then the embedded-jasper dependency actually causes things to break. The error isn't in this project, but a fix for this error still break something else which is bad :/

java.io.FileNotFoundException: Jar URL cannot be resolved to absolute file path because it does not reside in the file system: war:jar:file:/home/james/Sandboxes/property-management/web/build/libs/property-management-web-1.3.3-SNAPSHOT.jar!/lib/swagger-spring-mvc-ui-0.4.jar

**Comment by amccloud** [comment]
@pacey I too am seeing the same problem. Removing org.apache.tomcat.embed:tomcat-embed-jasper fixes the issue.

**Comment by panshul007** [comment]
If I include the org.apache.tomcat.embed:tomcat-embed-jasper dependency in my maven build, spring boot embedded tomcat fails to start up. Do I need to exclude something from the Spring boot jar?

**Comment by adrianbk** [comment]
The plan is to remove sdoc.jsp from the webjar and replace with an appropriate html file. We want to remove all of the hassle that including a jsp is causing.

**Comment by pacey** [comment]
Sounds like a good idea :+1:
