### ISSUE TITLE
UI stalling when API returns a ResponseEntity<String> 

### ISSUE THREAD

**Issue by agentgonzo** [springfox/springfox#50]
I'm using 0.4.0 and springMVC running in jetty.

When I have my API definitions as returning a ResponseEntity<String> object (or any derived class from HttpEntity, the UI will stall at "fetching resource <api>: http://localhost:8085/api-docs/core/metrics?api_key=special-key"

If I make it return a String, or Object, then it will work fine. Strangely, the XML returned when accessing the data directly is exactly the same.

Good:
    @RequestMapping(method = RequestMethod.GET, value="/v0.1/test", produces = CONTENT_TYPE)
    @ApiOperation(value = "Register DNS service name", notes = "A Path representing the DNS name to register is pas")
    @ResponseBody
    public Object test() {
        return null;
    }

Bad:
    @RequestMapping(method = RequestMethod.GET, value="/v0.1/test", produces = CONTENT_TYPE)
    @ApiOperation(value = "Register DNS service name", notes = "A Path representing the DNS name to register is pas")
    @ResponseBody
    public ResponseEntity<String> test() {
        return null;
    }

**Comment by datumgeek** [comment]
https://github.com/springfox/springfox/issues/50#issuecomment-17469275
error in swagger-ui saying toLowerCase is not a function of undefined.
i had a similar error and believe it was fixed by not using any capital letters in the path variable
![image](https://user-images.githubusercontent.com/22680176/29496512-3eadbf0e-8591-11e7-883b-cd2855dd7f57.png)
