### ISSUE TITLE
Api Versioning Best Practices

### ISSUE THREAD

**Issue by mressler** [springfox/springfox#594]
Swagger gurus,

First, thanks for an amazing documentation library.  You make me look like a hero to our partner organizations.

Second, I'm now running into the need to version my API.  I'm planning on using custom vendor MIME-types as suggested in [this article](http://captechconsulting.com/blog/jens-alm/versioned-validated-and-secured-rest-services-spring-40-1).  Naturally, I want whatever versioning method I choose to play nicely with my documentation engine of choice - Swagger.

The docs mention using Resource Listings to version your API, but I haven't found any good examples of how to set this up.  My first thought was to include multiple `SwaggerSpringMvcPlugin`s, but since the path to access my resources won't be changing in new API versions, I won't be able to use the `includePatterns` method to filter out API v1 vs API v2.  It would seem like I'd need to either filter by class name, package, or something else (maybe annotation?).

Has anyone done this to great success?  Am I thinking about this correctly?  Any good examples out there of versioned API listings using Swagger?

Thanks!

**Comment by mressler** [comment]
Swagger team,

Bummed to not get a response yet, but, undaunted, I'd be happy to carry this conversation to another location that is more trafficked.  Is StackOverflow the recommended location for such a question/request for pro-tip?

Thanks again!

**Comment by dilipkrish** [comment]
@mressler sorry for not getting back earlier... this is the best forum for issues/bugs/discussions. There are lots of exciting things coming up soon, and we've been busy trying to get a 1.0.0 release before focusing on that. 

I'm not a big fan of versioning RESTful services either in the uri nor in the media type as such. If you're at the liberty to (re)consider your choice; My personal preference (which has changed over time), is to create a new instance of the service and have that be outside of the uri-space of your service. One way to do that would be standing up a new service for instance, 

- One way could be ```http://order-service-v1.yourhost.com/```and the next version at ```http://order-service-v2.yourhost.com/```. 
- Or have a different contexts ```http://order-service.yourhost.com/v1/``` and the next version at ```http://order-service.yourhost.com/v2/``` 

The analogy I usually give is have you ever heard of amazon.com have a version in the uris or media types.

Here is an interesting article (and discussion) from way back when [on versioning and media types](https://www.subbu.org/blog/2009/12/media-types-and-plumbing). 

In any case, we're working on v2 of this library, and we're thinking of adding a predicate that takes a request mapping, rather than a regex string. The idea being that framework users would be able to provide a predicate to partition the uri-space according to their needs. In your case you'd be able to partition it based on media type. In case you're interested, the next gen work is happening [in this branch](https://github.com/martypitt/swagger-springmvc/tree/refactor/538/spike-to-seperate-models-and-dtos). Feedback and contributions are much appreciated!

**Comment by mressler** [comment]
Thank you for the great response.  I will certainly check out the branch!  Should I mark this as closed pending the 1.0 release?

Stripe seems to do an absolutely stellar job of versioning both its interface and documentation in lockstep and tying the version you're using to your Stripe account.  They've set the bar pretty damn high.

I was initially considering versioning using the context root given, which would make this an easier task from a documentation standpoint. Based on my few hours of investigation, it seemed the prevailing winds of discussion were blowing towards vendor versioned Media-Types and so here I find myself.

I'm certainly early enough in the project to consider other options.  Thank you for linking the article and discussion.

**Comment by dilipkrish** [comment]
I think there is a range of versioning approaches. I was at an interesting conference recently (Api360), where there was a slide comparing the continuum of versions changes of different apis over a period of time, and one end of the spectrum was _twitter_ which changed its api least frequently and the other end of that spectrum was _Stripe_. I'm unable to find the slides; but a lot depends on the nature of business and clients as well. 

One of the benefits of using a standard media types is that you have the advantage of shared understanding of the representations between client and server on how to act/navigate the resources it represents. Much like the browser knows how to handle html from the very first web page until now.  For e.g. if you used spring-hateoas/HAL combination. You get generic clients that knows how to make sense of a HAL document for free. The other thing to think about is; what you're looking to version is the message, and not how its formatted.

Here is another [interesting article](http://www.foxycart.com/blog/the-hypermedia-debate#.VP53xhbF-n5) by the  folks behind foxy cart, that might shed some practical intuitions.
