### ISSUE TITLE
ApiModelProperty.dataType() will not be used

### ISSUE THREAD

**Issue by MiErnst** [springfox/springfox#602]
With 0.9.5 the dataType() will not be used. Almost all other values are handled but not dataType(). Is there a reason for this?

**Comment by dilipkrish** [comment]
@MiErnst The reason this is not used is that we're prefer the natural data types over annotated data types. Couple of reasons for this
- ```dataType()``` can never reflect a type metadata completely. For e.g. if you were to render a data type that is a generic type or ```List<String>```
- philosophically the library takes the stand of providing the documetation with minimal annotation. So in that vein we mostly prefer annotations that enrich prose of the documentation, rather than the semantic. 

That said, in the upcoming release, you'd be able to access; a simpler to understand plugin model to provide your custom documentation to meet your needs.

**Comment by MiErnst** [comment]
Hi, thanks for the fast response.
> dataType() can never reflect a type metadata completely.
> philosophically the library takes the stand of providing the documetation with minimal annotation.

Ok, in my case we use a generic wrapper class and custom serializers/deserializers around IDs to be type safe. So the documented type should be for example `string` instead of `Wrapper<<Foo>>`. So the documentation should adjust to the code we are writing and not the code adjusts to the documentation. As long as I know the type which should be used, the annotated value should be in the lead as I want to explicitly override the default generated value. It would be nice if the dataType() property could also be handled in a 1.0.x version.

What are the release plans for a 2.0?

**Comment by jordanjennings** [comment]
@dilipkrish Is dataType officially going to be honored with 2.0, or will there just be the plugin model mentioned that will allow us to implement it ourselves easily? I'd love to see it natively implemented, at least for primitive types and String. I have many cases where I want to use the toString() representation of an object in a service, and right now I can't properly document it.

**Comment by dilipkrish** [comment]
@jordanjennings @MiErnst  Just added support for this is 2.0
