### ISSUE TITLE
springfox libs are breaking spring(boot) features

### ISSUE THREAD

**Issue by adrianbk** [springfox/springfox#638]
see: https://github.com/springfox/springfox-demos/blob/master/swagger2/build.gradle
Remove the sprigfox dependencies and the web-jars work. 
This log message may be related:
```
2015-04-01 23:54:39.934  WARN 29587 --- [           main] o.s.c.a.ConfigurationClassEnhancer       : @Bean method SwaggerCommonConfiguration.swaggerProperties is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details
20```

**Comment by adrianbk** [comment]
@dilipkrish is this related to prop..placholderconfig... we mentioned today?

**Comment by dilipkrish** [comment]
Yup definitely. As the message says adding a static modifier should fix this. Is it breaking anything?

**Comment by adrianbk** [comment]
not compile wise but it stops spring from serving static content.

**Comment by dilipkrish** [comment]
Bummer! If you push the code up when ye at a stopping point I'll take a look

**Comment by dilipkrish** [comment]
Yup I think that is it. It needs to be a static bean
> Resolving ${...} placeholders in <bean> and @Value annotations

> In order to resolve ${...} placeholders in <bean> definitions or @Value annotations using properties from a PropertySource, one must register a PropertySourcesPlaceholderConfigurer. This happens automatically when using <context:property-placeholder> in XML, but must be explicitly registered using a static @Bean method when using @Configuration classes. See the "Working with externalized values" section of @Configuration Javadoc and "a note on BeanFactoryPostProcessor-returning @Bean methods" of @Bean Javadoc for details and examples.

**Comment by who** [comment]
I think I'm hitting some sort of manifestation of this issue.  

In one of my `@Configuration` classes, I use a static `@Bean PropertySourcesPlaceholderConfigurer` to read values from a config file, and then later use `@Value` substitution to inject these into my persistence config layer.

Ever since [commit a63eb24](https://github.com/springfox/springfox/commit/a63eb2427926e86e0c476e7ae6136692cdc8ea56), my  `PropertySourcesPlaceholderConfigurer` seems to have no effect, and therefor my `@Value` substitution fails.
