### ISSUE TITLE
operationId is not guaranteed to be unique

### ISSUE THREAD

**Issue by dilipkrish** [springfox/springfox#682]
An example of the naive implementation failing is a definition for request mappings like the following

```java
@RequestMapping(method=RequestMethod.GET, value={"/campaigns","/campaigns/{id}"})
public String getCampaignDetails(Model model,
     @RequestParam(value="id", required=false) Long id,
     @PathVariable("id") Long id2)
{
}
```
Another scenario:
```java
@RequestMapping(method=RequestMethod.GET, value={"/campaigns","/campaignsAlias"})
```

This bug relates to #659

**Comment by adrianbk** [comment]
Another scenario is 2 spring controllers which happen to have the same method names and http methods for 2 different request mappings.

**Comment by adrianbk** [comment]
@who not sure if you want to have a look at this bug - we need to guarantee that the operationId is guaranteed to be unique

**Comment by who** [comment]
@adrianbk @dilipkrish Upon finding a duplicate operationId while parsing request mappings, should we:
1. throw an exception
2. rename the operationId
3. other ?

**Comment by adrianbk** [comment]
We need to change the generated id to include something else to make it unique enough.

**Comment by adrianbk** [comment]
Not sure if no.2 is straightforward - at the point where we create the operationId we don't know about all other operations and they're id's. It's probably going to have to include the path somehow - which is rather nasty!

I'm not a fan no 1 because it means we are throwing an exception because springfox is not capable of conforming to the swagger spec (operationId must be unique)

**Comment by who** [comment]
> It's probably going to have to include the path somehow - which is rather nasty!

Well, now that authors can override the default operationId, it probably matters less that the default operationId is ugly.

What about the following case, when the author deliberately creates a duplicate?  Should we throw an exception in this case?

```java
   @ApiOperation(value = "", nickname = "thisIsADuplicateNickname")
   @RequestMapping(value = "/books", method = RequestMethod.GET)
   public Model getAllTheBooks() {
        ...
   }

   @ApiOperation(value = "", nickname = "thisIsADuplicateNickname")
   @RequestMapping(value = "/pets", method = RequestMethod.GET)
   public Model getAllThePets() {
        ...
   }
```

**Comment by who** [comment]
Another option would be to alter my recent PR so that operationId is never automatically created, and it's only present if provided via the nickname field. If an author deliberately takes the action to create duplicate nicknames, we throw an exception at them.

**Comment by adrianbk** [comment]
@who we are probably less worried about users breaking the swagger spec due to misuse of the swagger annotations - we really do not want the default behaviour of springfox to break the spec though. I suspect to implement a check like that will involve iterating over every operation after everything has been scanned - which we should probably avoid unless absolutely necessary.

**Comment by who** [comment]
@adrianbk In that case, it sounds like this is our situation:
1. Generated operationIds will be unique but ugly, as they will be based on the HTTP verb + URI
2. If an author changes nicknames in such a way that introduces duplicates, don't worry about throwing exceptions.

**Comment by adrianbk** [comment]
@who those sound correct. 
A further step would be to allow users to easily override how the ids are generated.

**Comment by adrianbk** [comment]
@dilipkrish @who any update on this?

**Comment by dilipkrish** [comment]
Unfortunately have had time to work on it/look into it. My 2cents; while the current solution is not accurate, it will work for 80% of the cases, may be more. The proposed solution needs some time to bake in/ feedback etc. I'd like to push this off to 2.1

**Comment by who** [comment]
I have been looking into this, but agree 2.1 should be the milestone, especially because there is a workaround (providing a nickname override).

The general strategy I am playing with is: for each URI handled by a `@RequestMapping` path, convert the URI pattern to a snake-cased function name, prepend the HTTP verb, and assign the result to `uniqueId`.

Sample: 

Path pattern | Generated uniqueId
-----------------|---------------------------
HTTP GET /v1/magazines/{magazine} | get_v1_magazines_magazine
HTTP POST /pets | post_pets

The reason for generating a snake-case uniqueId is so that downstream consumers can easily convert the snake case into other case formats.

**Comment by dilipkrish** [comment]
👍🏻

**Comment by dilipkrish** [comment]
@who do you have an update?

**Comment by who** [comment]
@dilipkrish 

I've hit some significant snags with the approach outlined above. 

**Snag 1: **
If Springfox uses any string replacement logic in the process of generating an operationId, there is reduced guarantee of api-wide operationId uniqueness.

Example:

RequestMapping | generated operationId
----------------------  | -----------------------------
| `@RequestMapping(value = { "/pets/{id}"}, method=RequestMethod.GET)` | get_pets_id
| `@RequestMapping(value = { "/pets_id}"}, method=RequestMethod.GET)` | get_pets_id

**Snag 2: **
Because `@RequestMapping` can contain a set of methods and values, we may have to concat them, yielding large/strange operationIds and reduced likelihood of uniqueness.

Example:
RequestMapping | generated operationId
----------------------  | -----------------------------
| `@RequestMapping(value = { "/a", "/b", "/c"}, method=RequestMethod.GET)` | get_a_b_c 
| `@RequestMapping(value = { "/a_b_c"}, method=RequestMethod.GET)` | get_a_b_c 

Essentially, because RequestMapping is so flexible, generating unique operationIds for all of its permutations and idiosyncrasies may be a losing battle. Because of this, I am thinking that perhaps it would indeed be prudent to turn off automatic operationId creation entirely, and make it entirely manual via the nickname field, should Springfox users provide one.

**Comment by dilipkrish** [comment]
@who It seems like for *snag 1* we could just handle it post creating all the operations using a combination of [ApiDescriptionReader and ApiDescriptionBuilder](https://github.com/springfox/springfox/blob/42036696252d1635d976c463f18e9eadeff05799/springfox-spring-web/src/main/java/springfox/documentation/spring/web/scanners/ApiDescriptionReader.java#L65-L71) and add a number as a suffix i.e. *get_pets_id0, get_pets_id1*

About *snag 2* that should never be the case because that request mapping (the first one) will always generate *get_a, get_b and get_c* and **NOT** *get_a_b_c*

**Comment by rajeshkamal** [comment]
Hi,

I am using the 2.1.0 Springfox release. I make sure to provide proper meaningful and unique nicknames across all our controllers. So, I really do not want Springfox to add the additional uniqueness strings something like "UsingGET" etc.

The generated operation ids or java code looks like this, If you look at each of the method names, they are already unique and convey meaningful information. I really do not want the Using part to be appended. I agree that in some scenarios it might be helpful when the developers who do not provide nicknames. But if a nickname is provided then, we should definitely leave the responsibility to the users/developers and not override their settings. Or provide any other mechanism to get the name as what I want to. 

Rack Controller.

getRacksUsingGET()
getRackUsingGET(String)
getAlertsUsingGET1(String, String)
getSetupConfigUsingGET(String)
updateSetupConfigUsingPUT(String, RackConfig)
getEventsUsingGET1(String, String)
getHostsUsingGET2(String)
getIpReAllocationUsingGET(String)
rerunIpReAllocationUsingPUT(String)
performIpReAllocationUsingPOST(String)
cancelIpReAllocationUsingDELETE(String)
getSwitchesUsingGET(String)

**Comment by miguelruizdev** [comment]
For anyone wanting to customize `operationId` in their swagger definition: https://stackoverflow.com/questions/38821763/how-to-customize-the-value-of-operationid-generated-in-api-spec-with-swagger
