### ISSUE TITLE
Controller bean class matters in Resource Group (Java)

### ISSUE THREAD

**Issue by HiPwrD64** [springfox/springfox#707]
Hi guys,

I'm not sure if this is by design or a possible bug, so I'll pose this as a question:

In springfox.documentation.service.ResourceGroup, the equals() method compares the underlying bean class of the scanned Controller via: "equal(this.controllerClazz, rhs.controllerClazz)".

Now, consider an implementation where a series of Controllers provide a logical separation of rest api (say Go.dothis() at "GET /foo/dothis" and No.dontdothis() at "GET /foo/dontdothis"), all intended to be within a same physical resource group (i.e. "/foo").

Because of the controllerClazz comparison in equals() in ResourceGroup, the hash set used in SpringGroupStrategy will always replace ResourceGroup(foo, Go) with ResourceGroup(foo, No) (or vice versa, depending on ordering) from above example.  Due to the equals() method, swagger annotation @Api(value="foo") on both Go and No classes will yield the same behavior.

So my question is: Is this behavior by design in springfox 2?

**Comment by dilipkrish** [comment]
Based on the type of documentation it should pick [ClassOrApiAnnotationResourceGrouping](https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/ClassOrApiAnnotationResourceGrouping.java). The plugins manager defaults to the SpringGroupStrategy only if [no other plugin was found](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/DocumentationPluginsManager.java#L141-L143).

Needless to say since its a plugin model you can bring in your own strategy.

**Comment by HiPwrD64** [comment]
Thanks, I suspected that I would have to supply a custom strategy here.  

So it looks like @Autowired ResourceGroupingStrategy groupingStrategy in springfox.documentation.spring.web.readers.operation.OperationTagsReader throws a NoUniqueBeanDefinitionException due to multiple ResourceGroupingStrategy when a custom grouping strategy is injected into context as a Plugin.

Is there a trick to getting around this?  Thanks again.

**Comment by dilipkrish** [comment]
Hmm I think it's a bug that it's not using the plugin manager. Thanks for catching that! Ideally it should use the plugin manager to resolve it. Care to submit a pr for that?
