### ISSUE TITLE
@ModelAttribute is not visible in documentation

### ISSUE THREAD

**Issue by mandysingh** [springfox/springfox#725]
I am using swagger 2.0, I have some get type request methods which have @ModelAttribute type annotation on a parameter, but swagger doesn't show this in documentation, although I can see this in logs:
DEBUG springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander:79] Expanding parameter type: class <class-name>
where <class-name> is the type of parameter on which @ModelAttribute annotation is put.

**Comment by dilipkrish** [comment]
What does your model look like?

**Comment by mandysingh** [comment]
Thanks for replying, its a class which implements Serializable interface, it has usual getters and setters for its fields with one difference that setter method returns this object  apart from setting the field.
And once I make the return type as void for my setters, swagger starts displaying this in documentation as expected.

**Comment by dilipkrish** [comment]
Yeah that is by design. We want to use setters to infer model information, perhaps separate that concern into a builder of its own?

**Comment by soulrebel** [comment]
Consider the following example:

```java
@RequestMapping("/api/resource/{id}/{objAttr}")
public class MyController {

  @Autowired
  private Service service;

  public static class ReqParams {
    @NotNull
    @Pattern(regexp = "[0-9]+")
    public final String id;
    @Valid
    @NotNull
    public final MyObj myObj;

    ReqParams(String id, MyObj myObj) {
        this.id = id;
        this.myObj = myObj;
    }
  }

  @ModelAttribute()
  public EcuParams parseRequest(
      @PathVariable("id") String id,
      @PathVariable("objAttr") String objAttr,
      @RequestParam("anotherAttr") String anotherAttr) {
    return new ReqParams(id, new MyObj(objAttr, anotherAttr));
  }

  @RequestMapping(method = RequestMethod.GET)
  public ResponseEntity<Example> get(@Valid ReqParams params) {
    return ResponseEntity.ok(service.get(params.id, params.myObj));
  }
  // ... many more method enjoy the ReqParams avoinding repeated @PathVariable and so on...
}
```

The ReqParams is immutable and not fit to infer parameter names through setters (uses a nested object).
Why simply not use the parseRequest method, which has to have all the usual parameter annotations? It can be found just by following types and annotations.

**Comment by soulrebel** [comment]
@dilipkrish do I open another issue? is something not clear?

**Comment by dilipkrish** [comment]
@soulrebel Sorry this was a result of a mass closing of "questions". Yeah perhaps create a new feature request. Your request was perfectly valid. 

One thing I would say is that currently we do not chase annotations that are "hanging in the air" so to say. For e.g. we haven't added support for `@ExceptionHandler` or `@ModelAttributes` in your case that are somewhere in the class path. They are usually inlined in the method definition. Adding to this is the complexity of inheritance hierarchy in what is a pure DTO. So, In general I'm leaning towards having that be an extensibility feature, but I'm open to being convinced otherwise by the community :)

Also would be awesome if you'd be willing to "sponsor" this feature via a PR, especially since you're familiar with the requirement as well.
