### ISSUE TITLE
Using Maps

### ISSUE THREAD

**Issue by rcruzper** [springfox/springfox#828]
Hi, I'm getting an error similar to https://github.com/springfox/springfox/issues/815
I have the following field in my response class:
private Map\<String, Boolean\> permissions;

I'm using springfox-swagger2 version 2.0.3 and generates the json as follows:
"permissions": {
  "type": "object",
  "additionalProperties": {
    "type": "boolean"
  }
}

And swagger-ui version 2.1.0 shows this:
![captura de pantalla 2015-07-02 a las 16 31 23](https://cloud.githubusercontent.com/assets/1263202/8479399/da2a3956-20d7-11e5-9f0b-7104cbe7b74f.png)

I'm expecting something like this:
permissions: {
  "key": boolean
}

Am I missing something? Is there a bug?

**Comment by dilipkrish** [comment]
I think this is a bug in the swagger-ui.

**Comment by cabbonizio** [comment]
@rcruzper what does your definition in your pojo look like?   I was able to get the additional properties to expand, however it's appears to be more of an ArrayList as opposed to a Map.  I was satisfied with this for the moment, but it's not really accurate since I would rather have clients reading documentation on my service to know they are getting back a Map.   

I don't think Swagger UI can handle Maps yet, but I know many people have been asking for this and there are open issues on the Swagger UI GitHub site.  Until that gets fixed I don't believe the Spring Fox guys can resolve it.   

@dilipkrish do you agree?  I also I saw you added this to the 2.0.4 milestone is there a SpringFox fix you have in mind for this?

**Comment by rcruzper** [comment]
@cabbonizio this is the definition of the attribute in my pojo:
private Map\<String, Boolean\> permissions;

**Comment by dilipkrish** [comment]
@cabbonizio I just added the milestone so that there is a notion of when this question was asked. But yeah like you said, we just need to wait for swagger-ui to implement support for maps.

**Comment by cabbonizio** [comment]
@rcruzper I have some use of Maps also was just curious what you were using, but really a Map is a Map i guess :)

@dilipkrish thanks for adding this to the milestone so we can track it.   This is documentation feature many of us are looking for.

**Comment by dilipkrish** [comment]
Closing this question in preparation for 2.1.0
