### ISSUE TITLE
overflow-y

### ISSUE THREAD

**Issue by wind57** [springfox/springfox#840]
We have a small issue where not everything is visible on our html page, here is what I mean :

<img width="1098" alt="screen shot 2015-07-10 at 1 50 48 pm" src="https://cloud.githubusercontent.com/assets/932639/8617271/dccc1d9e-270a-11e5-9a58-9bae80b07efd.png">

From what I've seen a simple overflow-y : scroll would solve it.

**Comment by dilipkrish** [comment]
Seems like a swagger-ui issue... Probably should report it on that project.

**Comment by wind57** [comment]
this may sound weird - I haven't done much swagger, isn't springfox a continuation of swagger?

**Comment by dilipkrish** [comment]
It can be a little confusing :open_mouth: 

Swagger Spec is a specification
Swagger Api - an implementation of that specification that supports jax-rs, restlet, jersey etc.
Springfox libraries in general - is an another implementation of the specification focused on the spring based ecosystem
Swagger.js and Swagger-ui - Are client libraries in javascript that can consume swagger specification
*springfox-swagger-ui* - the one that you're using most likely based on your issue, is just packaging swagger-ui in a convenient way so that spring services can serve it up.

Hope that helps
