### ISSUE TITLE
Support Java 8 "-parameters"

### ISSUE THREAD

**Issue by mkotsbak** [springfox/springfox#900]
Please add support for parameter names enabled by "-parameters" with Java 8.x: 

https://docs.oracle.com/javase/tutorial/reflect/member/methodparameterreflection.html

Workaround until it is added: add "-g:vars" javac option instead/in addition to "-parameters".

**Comment by dilipkrish** [comment]
Not sure what we need to do here. It is supported via @JsonProperty annotations already and the `-parameters` option is library consumer specific.

**Comment by mkotsbak** [comment]
Well, it should also for the Spring integration support 

org.springframework.web.bind.annotation.PathVariable and org.springframework.web.bind.annotation.RequestParam

also. Both of these don't need the "value" parameter when compiled with "-parameters" in Java >=8.x.

**Comment by dilipkrish** [comment]
@mkotsbak I think this should be taken care off by springs parameter name discoverer

**Comment by mkotsbak** [comment]
It works with Spring MVC, just not with Springfox.

**Comment by dilipkrish** [comment]
Little 😕. 

Springfox relies on spring for parameter names. Example perhaps where it's not working?

**Comment by mkotsbak** [comment]
public @ApiResponseObject User updateUser(
            @PathVariable long userId) {...}

Here the name "userId" is not included in Springfox.

**Comment by dilipkrish** [comment]
@mkotsbak I know what the problem is. I was hoping for pointers to where there is a gap in springfox. We rely on [spring to provide a name](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/readers/parameter/ParameterNameReader.java#L52-L55). If none available is when we provide some default names.

In either case, Unless Im missing something totally obvious, if the code is compiled without the debug flag on or the `-parameters` option in java 8 there isn't much we can do right?

**Comment by mkotsbak** [comment]
That means it could be a bug in Spring?

No, it is not needed. Spring itself is able to get the parameters without it, just by the annotations.

**Comment by dilipkrish** [comment]
@mkotsbak you were right. I discovered a bug where the parameter names were not being detected correctly. Thanks again for reporting!

**Comment by mkotsbak** [comment]
Great! When is it expected to be released?

**Comment by dilipkrish** [comment]
in the next week... waiting to close out all the bugs in 2.3.0
