### ISSUE TITLE
@ApiImplicitParam: "array" dataType is getting resolved into "type":"ref"

### ISSUE THREAD

**Issue by anny-ts** [springfox/springfox#902]
Hi,
i have rest method where one of the implicit parameters is an array.
When i use @ApiImplicitParam annotation with dataType = "array" it is resolved into 
* "type":"ref" in api docs 
* "undefined" in swagger-ui
```java
@ApiImplicitParam(name = "status_ids", required = false, allowMultiple = true, paramType = "query", dataType = "array")
public List<App> listApps(@ApiIgnore HttpServletRequest request) {
//some code here
}
```
i'm using springfox-swagger2 2.1.2.

Could you please advise what is the correct way to document implicit array parameter?

Thank you.

**Comment by dilipkrish** [comment]
Just fyi here is [the documentation](http://springfox.github.io/springfox/docs/current/#overriding-property-datatypes) on the expectation of overriding types like you have.

Also it should be defined as a child of the implicit params collection

```java
@ApiImplicitParams({
    @ApiImplicitParam(name = "status_ids", required = false, allowMultiple = true, paramType = "query", dataType = "array")
})
```

**Comment by anny-ts** [comment]
Thank you for quick response,
I'm using @ApiImplicitParam as a child of @ApiImplicitParams.

What i need is to describe all possible query parameters, where one of the parameters is an array.

```java
@ApiImplicitParams({
            @ApiImplicitParam(name = "app_id", required = false, dataType = "string", paramType = "query"),
            @ApiImplicitParam(name = "status_ids", required = false, allowMultiple = true, paramType = "query", dataType = "array"),
            @ApiImplicitParam(name = "limit", required = false, dataType = "int", paramType = "query")
    })
    @RequestMapping(method = GET)
    public List<App> listApps(@ApiIgnore HttpServletRequest request, @ApiIgnore HttpSession httpSession) {
    	String query = request.getQueryString();
        //some code here
    }
```

My question is: what dataType value should i use for implicit parameter to be resolved into "array" type.

**Comment by dilipkrish** [comment]
Change `allowMultiple = true, paramType = "query", dataType = "array"` to `allowMultiple = true, paramType = "query", dataType = "string"`. 

`dataType` as descibed in the link :point_up: the value should be able to resolve to a valid type in the `ClassLoader`

**Comment by vivin** [comment]
I apologize for reopening this issue (didn't want to create a duplicate one).

Based on the swagger specification, one of the allowed types for a query parameter is `"array"`. However, I can't seem to set this for an array of enums through the `@ApiImplicitParam` annotation for an object annotated with `@ModelAttribute`:

```java
@ApiImplicitParams({
    @ApiImplicitParam(name = "classifications", allowMultiple = true, paramType = "query", allowableValues = "ONE, TWO, THREE")
})
```
This seems to generate a swagger model with the type set to `"ref"`. As originally mentioned in this issue, I can't set the type to `"array"` because `dataType` needs to be a class that can be instantiated. I did set the type to `"string"`, but this simply sets `dataType` to `"string"`, and there is no `"items"` entry even though `allowMultiple` is `true`. I basically end up with this:

```json
{
    "enum": [
        "ONE",
        "TWO",
        "THREE"
    ],
    "in": "query",
    "name": "classifications",
    "required": false,
    "type": "ref"
}
```

The enum itself is called `Classification`, and the type of the `classifications` field within the `@ModelAttribute`-annotated class is `Classification[]`.

I tried creating a type resolver to resolve the array type `Classification` to `String`, but I still end up with `ref`. Removing the `@ApiImplicitParams` annotation completely ends up giving me this:

```json
{
    name: "classifications",
    in: "query",
    required: false,
    type: "array",
    items: {
        $ref: "#/definitions/"
    },
    collectionFormat: "multi"
}
```

But this doesn't have the list of enum values or the item type I want (`"string"`). What is the correct way to accomplish this?

**Comment by dilipkrish** [comment]
@vivin I fixed a subtle bug with it, but it should be available when we release 2.4.0. details in the commit :point_up: Thanks for reporting!

**Comment by vivin** [comment]
@dilipkrish Thanks Dilip!

**Comment by vivin** [comment]
@dilipkrish One more question - I can't seem to find 2.4.x snapshot versions on the snapshot repo. Am I looking in the right place? Or should I try building directly from the source?

**Comment by dilipkrish** [comment]
Haven't upped the version yet. So u should find it @ 2.3.2-Snapshot. Details on how to get it it at http://springfox.io

**Comment by vivin** [comment]
@dilipkrish Thank you!

**Comment by smagellan** [comment]
strange results for Pojos: 
- swagger produces cool Model Schema for Data Type if @ApiParam(hidden=false) is applied
- swagger produces ordinary string for Data Type if @ApiParam(hidden=true)  and @ApiImplicitParam(name = "user", value = "user", required = true, dataType = "User") is applied
How can I configure Swagger to produce Model Schema (not ordinary string!) ?

**Comment by sumit1488** [comment]
I wanted to do the same using openapi 3. but there is no allowMultiple = true.
Any Idea how to get the same things done in open api 3.
