### ISSUE TITLE
Support for Spring Boot Management endpoints

### ISSUE THREAD

**Issue by sbuettner** [springfox/springfox#910]
The `Swagger2Controller` uses the `@Controller` annotation which simplifies the registration for a Spring MVC controller. It would be great if this could be changed to allow its registration as a [MvcEndpoint](http://docs.spring.io/spring-boot/docs/1.3.0.M3/api/org/springframework/boot/actuate/endpoint/mvc/MvcEndpoint.html). This would allow the registration of the controller under the [management port](http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html#production-ready-customizing-management-server-port) of Spring Boots Actuator.

**Comment by dilipkrish** [comment]
@sbuettner not sure we want to show that endpoint in the management console. What is the use case thats driving this need?

**Comment by sbuettner** [comment]
Hi @dilipkrish. Assuming you only expose the management port internally this would allow to hide the documentation from the public and make it only privately accessible. Maybe you are developing multiple applications but you only want to provide a documentation that contains all apis from all services and not one for each application/microserver. You might then generate a documentation based on your complete api from all swagger documents.

I hope this makes things a little bit more clearer.

**Comment by dilipkrish** [comment]
@sbuettner not entirely...

Currently all the swagger controllers `Swagger2Controller`, `Swagger1Controller` and `ApiResourceController` are all ignored using @ApiIgnore so that they don't show up in the swagger docs.

Other than that they are all regular mvc enpoints activated via `@Controller` and `@RequestMapping` annotations. Are you suggesting we implement MvcEndpoint interface explicitly? I thought that was an either or option. Is that not correct?
